# the Hebrew stopwords
hebrew_stopwords = ["את",
                    "זה",
                    "על",
                    "אבל",
                    "של",
                    "עם",
                    "הוא",
                    "אם",
                    "כי",
                    "יש",
                    "גם",
                    "או",
                    "היה",
                    "הזה",
                    "איך",
                    "שהוא",
                    "שזה",
                    "הייתי",
                    "אחרי",
                    "הם",
                    "וזה",
                    "עד",
                    "לפני",
                    "יהיה",
                    "והוא",
                    "וגם",
                    "אחר",
                    "הייתה",
                    "היו",
                    "ויש",
                    "זו",
                    "ב",
                    "ה",
                    "ו",
                    "כ",
                    "ל",
                    "מ",
                    "ש",
                    "וה",
                    "וכ",
                    "ול",
                    "וש",
                    "וכש",
                    "כש",
                    "שה",
                    "ולכש",
                    "ולכשה"]

# the extended Hebrew stopwords
hebrew_stopwords_ex = ["את",
                       "זה",
                       "על",
                       "אבל",
                       "של",
                       "עם",
                       "הוא",
                       "אם",
                       "כי",
                       "יש",
                       "גם",
                       "או",
                       "היה",
                       "הזה",
                       "איך",
                       "שהוא",
                       "שזה",
                       "הייתי",
                       "אחרי",
                       "הם",
                       "וזה",
                       "עד",
                       "לפני",
                       "יהיה",
                       "והוא",
                       "וגם",
                       "אחר",
                       "הייתה",
                       "היו",
                       "ויש",
                       "זו",
                       "ב",
                       "ה",
                       "ו",
                       "כ",
                       "ל",
                       "מ",
                       "ש",
                       "וה",
                       "וכ",
                       "ול",
                       "וש",
                       "וכש",
                       "כש",
                       "שה",
                       "ולכש",
                       "ולכשה",
                       "לא",
                       "היא",
                       "שלא",
                       "ולא",
                       "כן",
                       "שהיא"]

# the original English stopwords
stopwords = ["a",
             "about",
             "above",
             "across",
             "after",
             "again",
             "against",
             "all",
             "almost",
             "alone",
             "along",
             "already",
             "also",
             "although",
             "always",
             "among",
             "an",
             "and",
             "another",
             "any",
             "anybody",
             "anyone",
             "anything",
             "anywhere",
             "are",
             "area",
             "areas",
             "around",
             "as",
             "ask",
             "asked",
             "asking",
             "asks",
             "at",
             "away",
             "b",
             "back",
             "backed",
             "backing",
             "backs",
             "be",
             "because",
             "become",
             "becomes",
             "became",
             "been",
             "before",
             "began",
             "behind",
             "being",
             "beings",
             "best",
             "better",
             "between",
             "big",
             "both",
             "but",
             "by",
             "c",
             "came",
             "can",
             "cannot",
             "case",
             "cases",
             "certain",
             "certainly",
             "clear",
             "clearly",
             "come",
             "could",
             "d",
             "did",
             "differ",
             "different",
             "differently",
             "do",
             "does",
             "done",
             "down",
             "downed",
             "downing",
             "downs",
             "during",
             "e",
             "each",
             "early",
             "either",
             "end",
             "ended",
             "ending",
             "ends",
             "enough",
             "even",
             "evenly",
             "ever",
             "every",
             "everybody",
             "everyone",
             "everything",
             "everywhere",
             "f",
             "face",
             "faces",
             "fact",
             "facts",
             "far",
             "felt",
             "few",
             "find",
             "finds",
             "first",
             "for",
             "four",
             "from",
             "full",
             "fully",
             "further",
             "furthered",
             "furthering",
             "furthers",
             "g",
             "gave",
             "general",
             "generally",
             "get",
             "gets",
             "give",
             "given",
             "gives",
             "go",
             "going",
             "good",
             "goods",
             "got",
             "great",
             "greater",
             "greatest",
             "group",
             "grouped",
             "grouping",
             "groups",
             "h",
             "had",
             "has",
             "have",
             "having",
             "he",
             "her",
             "herself",
             "here",
             "high",
             "higher",
             "highest",
             "him",
             "himself",
             "his",
             "how",
             "however",
             "i",
             "if",
             "important",
             "in",
             "interest",
             "interested",
             "interesting",
             "interests",
             "into",
             "is",
             "it",
             "its",
             "itself",
             "j",
             "just",
             "k",
             "keep",
             "keeps",
             "kind",
             "knew",
             "know",
             "known",
             "knows",
             "l",
             "large",
             "largely",
             "last",
             "later",
             "latest",
             "least",
             "less",
             "let",
             "lets",
             "like",
             "likely",
             "long",
             "longer",
             "longest",
             "m",
             "made",
             "make",
             "making",
             "man",
             "many",
             "may",
             "me",
             "member",
             "members",
             "men",
             "might",
             "more",
             "most",
             "mostly",
             "mr",
             "mrs",
             "much",
             "must",
             "my",
             "myself",
             "n",
             "necessary",
             "need",
             "needed",
             "needing",
             "needs",
             "never",
             "new",
             "newer",
             "newest",
             "next",
             "no",
             "non",
             "not",
             "nobody",
             "noone",
             "nothing",
             "now",
             "nowhere",
             "number",
             "numbers",
             "o",
             "of",
             "off",
             "often",
             "old",
             "older",
             "oldest",
             "on",
             "once",
             "one",
             "only",
             "open",
             "opened",
             "opening",
             "opens",
             "or",
             "order",
             "ordered",
             "ordering",
             "orders",
             "other",
             "others",
             "our",
             "out",
             "over",
             "p",
             "part",
             "parted",
             "parting",
             "parts",
             "per",
             "perhaps",
             "place",
             "places",
             "point",
             "pointed",
             "pointing",
             "points",
             "possible",
             "present",
             "presented",
             "presenting",
             "presents",
             "problem",
             "problems",
             "put",
             "puts",
             "q",
             "quite",
             "r",
             "rather",
             "really",
             "right",
             "room",
             "rooms",
             "s",
             "said",
             "same",
             "saw",
             "say",
             "says",
             "second",
             "seconds",
             "see",
             "sees",
             "seem",
             "seemed",
             "seeming",
             "seems",
             "several",
             "shall",
             "she",
             "should",
             "show",
             "showed",
             "showing",
             "shows",
             "side",
             "sides",
             "since",
             "small",
             "smaller",
             "smallest",
             "so",
             "some",
             "somebody",
             "someone",
             "something",
             "somewhere",
             "state",
             "states",
             "still",
             "such",
             "sure",
             "t",
             "take",
             "taken",
             "than",
             "that",
             "the",
             "their",
             "them",
             "then",
             "there",
             "therefore",
             "these",
             "they",
             "thing",
             "things",
             "think",
             "thinks",
             "this",
             "those",
             "though",
             "thought",
             "thoughts",
             "three",
             "through",
             "thus",
             "to",
             "today",
             "together",
             "too",
             "took",
             "toward",
             "turn",
             "turned",
             "turning",
             "turns",
             "two",
             "u",
             "under",
             "until",
             "up",
             "upon",
             "us",
             "use",
             "uses",
             "used",
             "v",
             "very",
             "w",
             "want",
             "wanted",
             "wanting",
             "wants",
             "was",
             "way",
             "ways",
             "we",
             "well",
             "wells",
             "went",
             "were",
             "what",
             "when",
             "where",
             "whether",
             "which",
             "while",
             "who",
             "whole",
             "whose",
             "why",
             "will",
             "with",
             "within",
             "without",
             "work",
             "worked",
             "working",
             "works",
             "would",
             "x",
             "y",
             "year",
             "years",
             "yet",
             "you",
             "young",
             "younger",
             "youngest",
             "your",
             "yours",
             "z"]

# The following two lists based on: HaCohen-Kerner, Y., & Badash, H. (2016). Positive and negative sentiment words in
# a blog corpus written in hebrew. Procedia Computer Science, 96, 733-743.‏
# All rights reserved, do not copy or transmit without the permission of Professor HaCohen-Kerner!
positive_list_hebrew = ['רגוע', 'אהבה', 'נאה', 'טוב', 'נהדר', 'תקין', 'תודה', 'מבורך', 'שלם', 'ניצח', 'חרוץ', 'מחזק',
                        'עליזות', 'שמח', 'כיף', 'מוצלח', 'פיקח', 'כדאי', 'נעים', 'אושר', 'תקווה', 'אנרגיות חיוביות',
                        'בירך', 'יפה', 'חביב', 'יכול', 'נכון', 'נצחון', 'מתקן', 'ברכה', 'מאושר', 'טוב מאוד', 'עניו',
                        'יציב', 'אוהב', 'השתפר', 'חבל על הזמן', 'נהנה', 'אפשר', 'נפלא', 'בטחון', 'נאמן', 'שיפור',
                        'אהוב', 'אמון', 'משבח', 'ישר', 'קיווה', 'מתוקן', 'אמת', 'הצלחה', 'התלהבות', 'טעים', 'יופי',
                        'סוף העולם', 'צודק', 'ניצחון', 'מעולה', 'כיפי', 'יתרון', 'ביטחון', 'תיקון', 'משמח',
                        'מבין עניין', 'מצוין', 'להצליח', 'אופטימי', 'עליז', 'מותר', 'שיבח', 'מהמם', 'בטוח', 'שלווה']
negative_list_hebrew = ['דאגה', 'היסוס', 'עצב', 'רע', 'מתלונן', 'גינה', 'ייאוש', 'מדוכדך', 'חיסרון', 'כישלון', 'כשל',
                        'הפסיד', 'פסימי', 'עצוב', 'איום', 'אסון', 'ייאוש', 'דיכאון', 'סבל', 'זוועה', 'אסור', 'גרוע',
                        'סבל', 'רע', 'יש מקום לשיפור', 'עצב', 'מפחית', 'שגוי', 'אפאטיות', 'שבור', 'לא יכול', 'עגמימות',
                        'תלונה', 'מגנה', 'גינה', 'עקום', 'קללה', 'ייאוש', 'מדוכדך', 'חיסרון', 'דאון', 'להיכשל',
                        'כישלון', 'פחד', 'סכל', 'שנאה', 'שונא', 'קילל', 'חסר', 'עצלן', 'אנרגיות שליליות', 'הפסד',
                        'הפסיד', 'שקר', 'לא טוב', 'מכשול', 'מקולקל', 'פסימי', 'דוחה', 'עגום', 'עצוב', 'מעציב', 'מתנשא',
                        'קלקול', 'מקלקל', 'חשוד', 'כעור', 'מכוער', 'מבאס', 'איום', 'רפה', 'נסוג', 'נסיגה', 'חשש',
                        'שוגה', 'כועס', 'יהיר', 'מקולל', 'תבוסה', 'דחוי', 'ייאוש', 'הרס', 'אכזבה', 'מגעיל', 'זלזול',
                        'אגואיסט', 'כישלון', 'אסור', 'שנוא', 'בלתי נסבל', 'בלתי אפשרי', 'סבל', 'נורא ואיום', 'גרוע',
                        'בגידה', 'כיעור', 'על-הפנים', 'לא כדאי', 'לא נעים']

increasing_expressions_hebrew = ['ארוך', 'גאון', 'גדול', 'גם', 'די', 'דגול', 'המון', 'הצטיינות', 'הצלחה', 'הרבה',
                                 'וואחד', 'חזק', 'חכם', 'חמוד', 'הכי טוב', 'חשוב מאוד', 'יפה מאוד', 'טוב מאוד',
                                 'גדול מאוד', 'מאוד חשוב', 'ככל האפשר', 'מבסוט מאוד', 'ממש מדהים', 'סוף הדרך',
                                 'חבל על הזמן']
increasing_expressions_english = ['long', 'genius', 'big', 'also', 'pretty', 'great', 'lots', 'excellence', 'success',
                                  'much', 'strong', 'smart', 'cute', 'best', 'very important', 'very nice', 'very good',
                                  'very big', 'very important', 'as possible', 'very happy', 'really amazing',
                                  'excellent', 'out of this world']

decreasing_expressions_hebrew = ['בקושי', 'גמד', 'דל ', 'טיפה', 'טיפש', 'לא ', 'לאו', 'מטופש', 'מעט ', 'סתם', 'עלוב',
                                 'קטן', 'רע ', 'רק ', 'לא מוצלח', 'לא מספיק', 'מעט מאוד', 'על הפנים', 'לא כל כך']
decreasing_expressions_english = ['barely', 'dwarf', 'poor', 'pinch', 'foolish', 'no ', 'negative', 'stupid', 'few',
                                  'simply', 'wretched', 'small', 'bad', 'only', 'not successful', 'not enough',
                                  'very little', 'very bad', 'not so much']

time_expressions_hebrew = ['אחרי', 'אתמול', 'משך', 'מהירות', 'מוקדם', 'איטיות', 'מהלך', 'חודש', 'חודשיים', 'לאחר',
                           'לאט', 'מהר', 'אחרי זה', 'לפני זה', 'לפני כן', 'אחרי זמן מה']
time_expressions_english = ['afternoon', 'afternoons', 'birthday', 'day', 'days', 'evening', 'evenings', 'everyday',
                            'holiday', 'month', 'months', 'morning', 'mornings', 'night', 'nights', 'now', 'today',
                            'tomorrow', 'tonight', 'week', 'weeks', 'year', 'years', 'yesterday']

extended_time_expressions_hebrew = ['אביב', 'אז', 'אחר הצהריים', 'אתמול', 'באביב', 'באופן קבוע', 'באופן תדיר', 'בבוקר',
                                    'בבקרים', 'בדקה', 'בדקות', 'בדרך כלל', 'בהווה', 'בוקר', 'בזמן', 'בחג', 'בחודש',
                                    'בחודשים', 'בחורף', 'בחמישי', 'ביום', 'ביום הולדת', 'בימים', 'בכל יום', 'בלילה',
                                    'בלילות', 'במהלך', 'בנקודה', 'בסתיו', 'בעבר', 'בעוד', 'בערב', 'בערבים', 'בעתיד',
                                    'בקיץ', 'בקרים', 'בראשון', 'ברביעי', 'ברגע', 'ברגעים', 'בשבוע', 'בשבועות', 'בשבת',
                                    'בשישי', 'בשלישי', 'בשנה', 'בשני', 'בשניות', 'בשנייה', 'בשנים', 'בשעה', 'בשעות',
                                    'בתאריך', 'בתאריכים', 'בתקופה', 'בתקופות', 'דקה', 'דקות', 'האביב', 'הבוקר',
                                    'הבקרים', 'הדקה', 'הדקות', 'ההווה', 'הווה', 'הזמן', 'החג', 'החודש', 'החודשים',
                                    'החורף', 'החמישי', 'היום', 'היום הולדת', 'הימים', 'הלילה', 'הלילות', 'המחר',
                                    'הנפוץ', 'הנקודה', 'הסתיו', 'העבר', 'הערב', 'הערבים', 'העתיד', 'הקיץ', 'הראשון',
                                    'הרביעי', 'הרגע', 'הרגעים', 'השבוע', 'השבועות', 'השבת', 'השישי', 'השלישי', 'השנה',
                                    'השני', 'השניות', 'השנייה', 'השנים', 'השעה', 'השעות', 'התאריך', 'התאריכים',
                                    'התקופה', 'התקופות', 'ואביב', 'ואז', 'ואחר הצהריים', 'ואתמול', 'ובאופן קבוע',
                                    'ובאופן תדיר', 'ובדרך כלל', 'ובוקר', 'ובמהלך', 'ובעוד', 'ובקרים', 'ודקה', 'ודקות',
                                    'והווה', 'וזמן', 'וחג', 'וחודש', 'וחודשים', 'וחורף', 'וחמישי', 'ויום',
                                    'ויום הולדת', 'וימים', 'וכאשר', 'וכל יום', 'ולילה', 'ולילות', 'ולעיתים',
                                    'ולעיתים רחוקות', 'ולעתים קרובות', 'ולפעמים', 'ומחר', 'ונכון לעכשיו', 'ונפוץ',
                                    'ונקודה', 'וסתיו', 'ועבר', 'ועד', 'ועכשיו', 'וערב', 'וערבים', 'ועתיד', 'וקיץ',
                                    'וראשון', 'ורביעי', 'ורגע', 'ורגעים', 'ושבוע', 'ושבועות', 'ושבת', 'ושישי', 'ושלישי',
                                    'ושנה', 'ושני', 'ושניות', 'ושנייה', 'ושנים', 'ושעה', 'ושעות', 'ותאריך', 'ותאריכים',
                                    'ותקופה', 'ותקופות', 'זמן', 'חג', 'חודש', 'חודשים', 'חורף', 'חמישי', 'יום',
                                    'יום הולדת', 'ימים', 'כאשר', 'כל יום', 'לאביב', 'לאז', 'לאחר הצהריים', 'לבוקר',
                                    'לבמהלך', 'לבקרים', 'לדקה', 'לדקות', 'להווה', 'לזמן', 'לחג', 'לחודש', 'לחודשים',
                                    'לחורף', 'לחמישי', 'ליום', 'ליום הולדת', 'לילה', 'לילות', 'לימים', 'לכאשר',
                                    'לכל יום', 'ללילה', 'ללילות', 'למחר', 'לנקודה', 'לסתיו', 'לעבר', 'לעד', 'לעיתים',
                                    'לעיתים רחוקות', 'לעכשיו', 'לערב', 'לערבים', 'לעתיד', 'לעתים קרובות', 'לפעמים',
                                    'לקיץ', 'לראשון', 'לרביעי', 'לרגע', 'לרגעים', 'לשבוע', 'לשבועות', 'לשבת', 'לשישי',
                                    'לשלישי', 'לשנה', 'לשני', 'לשניות', 'לשנייה', 'לשנים', 'לשעה', 'לתאריך', 'לתאריכים',
                                    'לתקופה', 'לתקופות', 'מחר', 'נכון לעכשיו', 'נפוץ', 'נקודה', 'סתיו', 'עבר', 'עד',
                                    'עכשיו', 'ערב', 'ערבים', 'עתיד', 'קיץ', 'ראשון', 'רביעי', 'רגע', 'רגעים', 'שאז',
                                    'שאחר הצהריים', 'שאתמול', 'שבאופן קבוע', 'שבאופן תדיר', 'שבדרך כלל', 'שבוע',
                                    'שבועות', 'שבמהלך', 'שבעוד', 'שבקרים', 'שבת', 'שדקה', 'שדקות', 'שהווה', 'שזמן',
                                    'שחג', 'שחודש', 'שחודשים', 'שחורף', 'שחמישי', 'שיום', 'שיום הולדת', 'שימים',
                                    'שישי', 'שכאשר', 'שכל יום', 'שלילה', 'שלילות', 'שלישי', 'שלעיתים', 'שלעיתים רחוקות',
                                    'שלעתים קרובות', 'שלפעמים', 'שמחר', 'שנה', 'שני', 'שניות', 'שנייה', 'שנים',
                                    'שנכון לעכשיו', 'שנפוץ', 'שנקודה', 'שסתיו', 'שעבר', 'שעד', 'שעה', 'שעות',
                                    'שעכשיו', 'שערב', 'שערבים', 'שעתיד', 'שקיץ', 'שראשון', 'שרביעי', 'שרגע', 'שרגעים',
                                    'ששבוע', 'ששעה', 'ששעות', 'שתאריך', 'שתאריכים', 'שתקופה', 'שתקופות', 'תאריך',
                                    'תאריכים', 'תקופה', 'תקופות']
extended_time_expressions_english = ['afternoon', 'afternoons', 'birthday', 'commonly', 'constantly', 'current',
                                     'currently', 'date', 'dates', 'day', 'days', 'during', 'evening', 'evenings',
                                     'everyday', 'frequent', 'frequently', 'friday', 'future', 'generally', 'holiday',
                                     'hour', 'hours', 'infrequently', 'minute', 'minutes', 'moment', 'moments',
                                     'monday', 'month', 'months', 'morning', 'mornings', 'night', 'nights', 'now',
                                     'past', 'period', 'periods', 'present', 'rarely', 'regularly', 'saturday',
                                     'second', 'seconds', 'seldom', 'summer', 'sunday', 'then', 'thursday', 'time',
                                     'today', 'tomorrow', 'tonight', 'tuesday', 'until', 'usually', 'wednesday', 'week',
                                     'weeks', 'when', 'while', 'winter', 'year', 'years', 'yesterday']

doubt_expressions_hebrew = ['בערך', 'אני חושבת', 'למיטב הבנתי', 'אני מאמינה', 'איני בטוחה', 'איני זוכרת',
                            'אני לא זוכרת', 'אני לא בטוחה']
doubt_expressions_english = ['about', 'i think', 'as far as i can see', 'i believe', "I'm not sure", "i don't remember",
                             'i do not remember', 'i am not sure']

emotion_expressions_hebrew = ['אכזבה', 'בכי', 'התאכזב', 'וויכוח', 'חוויה', 'כעס', 'מאוס', 'מדוכא', 'מהמם', 'מעציב',
                              'מפריע', 'נמאס', 'עצב', 'עצוב', 'ריב', 'שמח']
emotion_expressions_english = ['disappointment', 'crying', 'disappointed', 'argument', 'experience', 'anger',
                               'repulsive', 'depressed', 'amazing', 'unfortunate', 'disturb', 'become repulsive',
                               'sadness', 'sad', 'fight', 'happy']

first_person_expressions_hebrew = ["אני", "אנחנו"]
first_person_expressions_english = ['I', "I'm", "I'll", "I'd", "I've", 'me', 'myself', 'me', 'my', 'mine', 'we',
                                    "we're", "we'll", "we'd", "we've", 'us', 'our', 'ours', 'ourselves', 'personally',
                                    'im']

second_person_expressions_hebrew = ["את ", "אתה ", "אתם", "אתן"]
second_person_expressions_english = ['you', 'your', 'yours', 'yourself', 'yourselves', "you're", "you'll", "you've",
                                     "you'd"]

third_person_expressions_hebrew = ["הוא", "היא", "הם", "הן"]
third_person_expressions_english = ['his', 'him', 'himself', 'he', 'hers', 'herself', 'her', 'has', 'it', 'its', "it's",
                                    'itself', 'she', 'they', 'them', 'their', 'theirs', 'themselves', 'another',
                                    'others', 'does', "doesn't", "he's", "she's", "they're", "he'll", "she'll",
                                    "they'll", "he'd", "she'd", "they'd"]

inclusion_expressions_hebrew = ['איזה', 'איזהו', 'איזשהו', 'איזושהי', 'וזה', 'כלשהו', 'כלשהי', 'כולם', 'משהו', 'כללי',
                                'כוללני', 'כל']
inclusion_expressions_english = ['which', 'who is', 'some', 'and this', 'any', 'everyone', 'something', 'general',
                                 'comprehensive', 'all']

power3_expressions_hebrew = ['התלהבות', 'מצוין ', 'אופטימי', 'מעולה', 'נפלא ', 'שלם', 'חבל על הזמן', 'משמח']
power3_expressions_english = ['enthusiasm', 'excellent', 'optimistic', 'excellent', 'wonderful', 'whole',
                              'out of this world', 'to cheer up']

power2_expressions_hebrew = ['יתרון', 'מותר', 'מהמם', 'אושר', 'ביטחון', 'נהנה', 'כיף', 'טוב']
power2_expressions_english = ['advantage', 'allowed', 'amazing', 'happiness', 'security', 'enjoy', 'fun', 'good']

power1_expressions_hebrew = ['שמחה', 'יכול', 'טוב', 'אפשר', 'יחסית טוב', 'נכון', 'מקפצה']
power1_expressions_english = ['joy', 'can', 'good', 'possible', 'relatively good', 'correct', 'springboard']

powerm1_expressions_hebrew = ['לא נעים', 'לא כדאי']
powerm1_expressions_english = ['unpleasant', 'not worth it']

powerm2_expressions_hebrew = ['דאגה', 'היסוס', 'עצב', 'חושש', 'יש מקום לשיפור', 'עצב', 'מפחית']
powerm2_expressions_english = ['worry', 'hesitation', 'sadness', 'afraid', 'there is room for improvement', 'sadness',
                               'reduces']

powerm3_expressions_hebrew = ['רע', 'מתלונן', 'מדוכדך ', 'חיסרון', 'כישלון', 'כשל', 'הפסיד ', 'פסימי']
powerm3_expressions_english = ['bad', 'complainant', 'despondent', 'disadvantage', 'failure', 'mistake', 'lost',
                               'pessimistic']

powerm4_expressions_hebrew = ['אסון', 'ייאוש', 'דיכאון', 'סבל', 'זוועה', 'אסור', 'גרוע', 'על הפנים']
powerm4_expressions_english = ['disaster', 'despair', 'depression', 'suffering', 'horror', 'forbidden', 'horrible',
                               'terrible']

# lists of words for classification by families of words
anorexia_family = ['באנורקסיה', 'אנורקסיה', 'אנורקסית', 'לאנורקסיה', 'האנורקס', 'אנורקטי', 'אנורקטית', 'אנורקטיות',
                   'מהאנורקסיות', 'שאנורקסיה', 'האנורקסיה', 'אנורקסיתתתתתתתתתת', 'אונרקסית', 'האנורקסיה', 'באנורקסיה',
                   'אנורקסיות', 'אנורקסיות', 'מאנורקסיה', 'האנורקס', 'אנורקסית', 'לאנורקסיה', 'שאנורקסיות', 'אנורקסיים',
                   'מהאנורקסיות', 'שאנורקסיות', 'שאנורקסיה', 'אנרוקסיה', 'מאנורקסיה', 'בולימיה', 'בולימית', 'בולימיות',
                   'בולימיות', 'הבולימית', 'הבולימיות', 'הפרעת אכילה', 'הפרעות אכילה']
anorexia_family_en = ['anorexia', 'aenorexia', 'anorexic', 'aenorexic', 'nervosa', 'anorexics', 'ED', 'eating disorder',
                      'spree', 'rage', 'mania']

food_family = ['נאכלת', 'אוכלת', 'ותאכל', 'אוכלים', 'האוכל', 'המאכל', 'מאכל', 'ואוכלת', 'ואכל', 'האכילה', 'שיאכלו',
               'לאכילה', 'אכלנית', 'יאכל', 'תאכלללללללל', 'שאכלו', 'באוכל', 'אוכלות', 'באוכלל', 'אכלתי', 'שאוכלים',
               'ללאכול', 'מאוכל', 'שאכלתי', 'ובאוכל', 'איכלה', 'מהאוכל', 'אכלו', 'אכל', 'אכילה', 'לאוכל', 'ואכלתי',
               'מהאכול', 'תאכלו', 'תאכל', 'שנאכל', 'ותאכלי', 'שואכלים', 'ממאכלים', 'תאכלייי', 'אוכל', 'שתיתיואכלתי',
               'מאכלים', 'אכלנו', 'שאוכלת', 'ולאכול', 'שהאוכל', 'שאוכל', 'שאכלתייי', 'תאכלי', 'באכילה', 'לאכול',
               'ושאוכל', 'ואוכל', 'אכלה', 'כשהאוכל', 'האכילו', 'ארוחת', 'הארוחת', 'ארוחות', 'וארוחות', 'וארוחת',
               'הארוחה', 'והארוחות', 'לארוחה', 'בארוחה', 'לארוחות', 'מהארוחת', 'ארוחה', 'לארוחת', 'תשתי', 'שתיה',
               'ושתיתי', 'שתיתיואכלתי', 'שתייה', 'שתיתי', 'שתי', 'ששתיתי', 'זלילת', 'זוללת', 'לזלול', 'הזלילה', 'בליסה',
               'שבלסתי', 'בולסת', 'הבהליסות', 'בלסתי', 'לבלוס', 'אוכל', 'אכילה', 'לאכול', 'אכלתי', 'יאכל', 'ארוחה',
               'ארוחת', 'ארוחות', 'תפריט', 'שתיה', 'שתיתי', 'מים', 'דיאט', 'בולמוס', 'נס', 'קפה', 'סוכר', 'סוכרזית',
               'פחמימות', 'הנישנושים', 'לנשנש', 'נשנושים', 'ונשנושים', 'נטרפת', 'טורפים', 'טעם', 'בטעם', 'מהטעם',
               'שהטעם', 'טעים', 'וטעים', 'לטחון', 'ללטחון', 'טחנתי']
food_family_en = ['eat', 'eats', 'eaten', 'eater', 'ate', 'eating', 'eater', 'food', 'foood', 'fooood', 'meal', 'meals',
                  'snack', 'snacks', 'snacker', 'snacking', 'breakfast', 'breakfasts', 'lunch', 'lunches', 'dinner',
                  'dinners', 'supper', 'suppers', 'gobble', 'gobbles', 'gobbling', 'wolf', 'wolfs', 'munch', 'munches',
                  'gorge', 'gorges', 'swallow', 'swallows', 'swallowing', 'dine', 'dines', 'dining', 'drink', 'drinks',
                  'drinking', 'sip', 'sips', 'sipping', 'slurp', 'slurps', 'slurping', 'lunchtime', 'dinnertime',
                  'suppertime', 'nourishment', 'nutrition', 'nutriment', 'nutriments', 'chow', 'cook', 'cooks',
                  'cooker', 'cooking', 'cuisine', 'groceries', 'victuals', 'grub', 'water', 'meal', 'meals', 'coffee',
                  'coffees', 'coke', 'cokes', 'soda', 'sodas', 'pop', 'sugar', 'sugars', 'saccharine', 'taste',
                  'tastes', 'tasting', 'taster', 'tasty', 'tasteless', 'drop', 'mouthful', 'stuff', 'stuffs',
                  'stuffing', 'stuffer', 'junk food', 'soda pop', 'gulp', 'gulps', 'gulping', 'wolf', 'wolfed', 'wolfs',
                  'wolfing', 'guzzle', 'guzzles', 'guzzling guzzled', 'guzzler', 'devour', 'devours', 'devoured',
                  'devouring']

fat_family = ['שמנה', 'ושמנה', 'מהשומנים', 'השומן', 'לשומן', 'השמנה', 'שמנמנה', 'שמנמונת', 'משמינים', 'שמנתי', 'שומנים',
              'השמנתי', 'משמין', 'שמנמן', 'ושמנה', 'השמנות', 'השומנים', 'השמנמנה', 'להשמין', 'שמן', 'משמינה', 'שמנה',
              'השמין', 'השמנצי', 'שומן', 'תשממיינווו', 'ומשמינה', 'השמן', 'שמנות', 'שמנמנות', 'שהשמנתי', 'השמינו',
              'שמנים', 'ושומני', 'פרה', 'דבה', 'פרהה', 'פרההה']
fat_family_en = ['fat', 'fatter', 'fattest', 'overweight', 'plump', 'plumper', 'plumpest', 'chubby', 'chubbier',
                 'chubbiest', 'heavy', 'heavier', 'heaviest', 'flabby', 'flabbier', 'flabbiest', 'pudgy', 'pudgier',
                 'pudgiest', 'corpulent', 'fatty', 'fatso', 'pig', 'pigs', 'weight', 'obese', 'blubber', 'overweight',
                 'obesity', 'hefty', 'heftier', 'heftiest', 'chunky', 'gigantic', 'massive', 'massively', 'huge',
                 'bloated', 'heffalump', 'elephant', 'glutton', 'gluttony', 'gluttons', 'binge', 'binging', 'stuff',
                 'stuffs', 'stuffing', 'yummy', 'pigging out']

ana_family = ['לאנה', 'אנות', 'אננה', 'האנה', 'פרואנה', 'מפראנה', 'לפראנה', 'פראני', 'הפראני', 'שאנה', 'אנה', 'מיות',
              'למיה', 'מיה', 'פרו- אנה', 'הפרו אנה', 'פרו אנורקסיה', 'פרו מיה', 'מפרו אנה', 'פרו-אנה', 'ופרו מיה',
              'לפרו-אנורקסיה', 'פרו מה', 'פרואנה', 'פרו-מיה', 'מהפרו אנה', 'פרו אנה', 'ופרו אנה']
ana_family_en = ['ano', 'ana', 'anna', 'pro-ano', 'proano', 'pro-ana', 'proana', 'pro-anna', 'proanna', 'mia',
                 'pro-anorexia', 'proanorexia', 'thinspo', 'thinspiration']

hunger_family = ['הרעב', 'שהרעבה', 'מורעבת1', 'רעבה', 'להרעבות', 'ההרעבות', 'תרעיבי', 'רעבים', 'מרעב', 'לרעוב', 'רעב',
                 'להרעיב', 'ההרעבה', 'הרעבה', 'ברעב', 'מרעיבה', 'מהרעב', 'מהרעבה', 'רררררררררעעבה', 'כשרעבים', 'הרעבתי',
                 'הצמא', 'הבולמוס', 'בולמוסון', 'בולמוס', 'הבולמוסים', 'בבולמוס', 'בולמוסים', 'לבולמוס', 'לבולמוסים']
hunger_family_en = ['hunger', 'hungers', 'hungering', 'hungered', 'hungry', 'hungryy', 'hungryyy', 'hungrier',
                    'hungriest', 'starve', 'starves', 'starved', 'starving', 'appetite', 'starvation', 'craving',
                    'cravings', 'crave', 'craved', 'hungriness', 'ravenous', 'famished', 'famishment', 'empty',
                    'emptier', 'emptiest', 'thirst', 'thirsty', 'thirstier', 'thirstiest', 'thirsting', 'malnutrition']

me_family = ['העצמי', 'עצמי', 'עצמית', 'עצמיי', 'העצמית', 'בעצמי', 'לעצמי', 'מעצמי', 'ואניי', 'אניש', 'משאני', 'ושאני',
             'שאני', 'ואני', 'אניי', 'שכשאני', 'ואניייייי', 'כשאניא', 'וכשאני', 'שאניא', 'אני', 'כשאני', 'אנייי', 'שלי',
             'שליייייייייי', 'שלנו', 'משלי', 'לשלי', 'שליי', 'אנוכי', 'ואנוכי']
me_family_en = ['I', 'me', 'myself', 'me', 'my', 'mine', 'we', 'us', 'our', 'ours', 'ourselves', 'personally']

vomiting_family = ['להקיא', 'שהקאתי', 'והקאה', 'הקאת', 'הקאתי', 'הקיא', 'כשהקאתי', 'ולהקיא', 'הקאות', 'הקאה', 'והקאתי',
                   'ההקאות', 'שמקיאות', 'מקיאה', 'בקיא', 'אקיא', 'להקיא', 'ומקיאה', 'מקיא', 'ולהקיא', 'הקיא', 'קיא',
                   'יקיא', 'כדורים', 'וכדורים', 'בכדורים', 'הכדורים', 'כדור', 'כדורי', 'משלשל', 'שלשלתי', 'למשלשלים',
                   'ומשלשלת', 'ולמשלשלים', 'ושלשלתי', 'המשלשלים', 'משלשלים', 'שצמתי', 'שצומות', 'לצום', 'צמתי', 'צמה',
                   'הצום', 'צומון', 'לצוםם', 'הקא', 'הקאתי', 'הקאה', 'הקאת', 'מקיא', 'מקיאת', 'מקיאה', 'שירותים',
                   'אסלה', 'כדור', 'כדורי', 'כדורים', 'משלשל', 'משלשלים', 'משלש']
vomiting_family_en = ['vomit', 'vomits', 'vomited', 'vomiting', 'vomiter', 'vomitt', 'vomittt', 'puke', 'pukes',
                      'puking', 'puked', 'barf', 'barfed', 'barfing', 'gag', 'gags', 'gagged', 'heave', 'heaves',
                      'heaving', 'heaved', 'retch', 'retching', 'retched', 'pill', 'pills', 'tablet', 'tablets',
                      'bathroom', 'bathrooms', 'toilet', 'toilets', 'diarrhea', 'fast', 'fasting', 'fasted', 'faster',
                      'faast', 'faaast', 'faasting', 'faaasting', 'purge', 'purges', 'purged', 'purging', 'laxatives',
                      'laxatives', 'diuretic', 'flush', 'flushing', 'skip', 'skips', 'skipped', 'skipping', 'restrict',
                      'restricts', 'restricted', 'restricting', 'control', 'controlled', 'uncontrolled', 'controls',
                      'controlling ', 'punish', 'punishes', 'punished', 'punishing']

pain_family = ['וכאבים', 'שכואב', 'להכאיב', 'שכאבו', 'כאבים', 'לכאב', 'הכאב', 'כואבת', 'וכואב', 'וכאבה', 'כואבות',
               'מהכאבים', 'הכאבי', 'כאב', 'בכאב', 'כואב', 'וכואבות', 'כאבו', 'וכאבי', 'כאבי', 'לכאוב', 'והכאב',
               'סובלים', 'שסובל', 'הסבל', 'סובלני', 'סבלתי', 'לסבול', 'הסובלים', 'שסובלים', 'לסבל', 'סובלת', 'יסבול',
               'נסבלת', 'שסבלתי', 'וסבל', 'סבל', 'שתסבול', 'קשים', 'ובקושי', 'שקשה', 'קשיים', 'לקושי', 'קשה', 'קשות',
               'וקשות', 'הקשה', 'בקושי', 'וקשה', 'חולשה', 'וחלשת', 'חלשות', 'חלש', 'חלשה', 'נחלשות', 'וחולשה', 'תבכו',
               'ובכיתי', 'ובוכה', 'וכשבכיתי', 'בכיתי', 'בכי', 'בכיינות', 'לבכות', 'בוכה', 'עייפה', 'עייפות', 'התעייפתי',
               'נוראי', 'הנוראית', 'נוראיים', 'נוראית', 'נורא', 'הנורא', 'התישה', 'הדמעות', 'דמעות', 'מדמעות', 'זועק',
               'זועקת', 'התחננתי', 'ומתחננת', 'נפלתי', 'התמוטטתי', 'להתמוטט', 'מלחמה', 'מלחמה', 'למלחמה', 'מהמלחמה',
               'נזק', 'הנזק', 'להרוס', 'שבורה', 'מכות', 'דיממתי', 'נשרוד', 'שנשרוד', 'בושה', 'הבושה', 'שברירי',
               'השברירי']
pain_family_en = ['pain', 'pains', 'hurt', 'hurts', 'hurting', 'ache', 'aches', 'ached', 'aching', 'weak', 'weaker',
                  'weakest', 'weakness', 'weaknesses', 'difficulty', 'difficult', 'suffer', 'sufferer', 'suffers',
                  'suffered', 'suffering', 'discomfort', 'discomforts', 'soreness', 'throb ', 'throbs', 'throbbing',
                  'throbbings', 'hard', 'harder', 'hardest', 'tough', 'tougher', 'toughest', 'cry', 'cried', 'cries',
                  'crying', 'crier', 'weep', 'weeps', 'wept', 'weeper', 'weeping', 'tear', 'tears', 'tired', 'tireder',
                  'tiredest', 'terrible', 'horrible', 'awful', 'terribly', 'awfully', 'horribly', 'fall', 'fell',
                  'falling', 'faint', 'faints', 'fainted', 'fainting', 'break down', 'broke down', 'breaking down',
                  'breakdown', 'fall apart', 'falling apart', 'fell apart', 'falls apart', 'war', 'wars', 'damage',
                  'damages', 'damaging', 'injury', 'injuries', 'injure', 'injured', 'injuring', 'shame',
                  'embarrassment', 'destroy', 'destroys', 'destroyed', 'destroying', 'destroyer']

anger_family = ['לעצבים', 'עצבים', 'ועצוב', 'עצובה', 'עצוב', 'בעצבים', 'מעצבנת', 'מעוצבנת', 'שהתעצבנתי', 'עצבנית',
                'מעצבן', 'ומתעצבנת', 'עצבנות', 'התעצבנתי', 'והדיכאון', 'ודיכאונית', 'לדיכאונות', 'לדכאון', 'בדיכאון',
                'הדיכאון', 'לדיכאון', 'דיכאון', 'בדיכי', 'פחדתי', 'מפחידים', 'פחד', 'מפחדי', 'מפחדת', 'פוחדת', 'פחדנית',
                'לפחד', 'להפחיד', 'בפחד', 'ופחד', 'פוחדים', 'אפחד', 'והפחד', 'מפחיד', 'נמאס', 'יימאס', 'מאוס',
                'ושיימאס', 'שנמאס', 'חרדה', 'מחריד', 'מחרידים', 'נחרדת', 'החרדות', 'באסה', 'מבאסים', 'מבאס', 'נואש',
                'נואשת', 'מאוכזב', 'מאוכזבת', 'כועס', 'כועסת', 'עצלה', 'עצלנית', 'ועצלנית', 'דחו', 'דחויה', 'אתאבד',
                'אאבד', 'התאבדות', 'שמתאבדים', '"להרוג את עצמי" גרוע', 'לחץ', 'הלחץ', 'תלחץ', 'בלחץ', 'מהלחץ', 'לוחץ',
                'אומלל', 'אומללים', 'אומללה', 'אכזר', 'האכזר', 'והאכזר', 'אכזריות', 'מרוסקת', 'מיואשת', 'ייאוש',
                'הייאוש', 'שהייאוש', 'למות', 'למוות', 'אשמה', 'האשמה', 'ייסורי', 'מצפון', 'לבד', 'בודד', 'בודדה',
                'נכשלת', 'נכשלתי', 'וניכשלתי', 'ניכשליתי', 'כישלון', 'הפסדתי']
anger_family_en = ['anger', 'angry', 'angrier', 'angriest', 'sad', 'sadder', 'saddest', 'sadness', 'mad', 'madder',
                   'maddest', 'depress', 'depresses', 'depressing', 'depressingly', 'depressed', 'depression',
                   'depressions', 'dejected', 'unhappy', 'unhappier', 'unhappiest', 'miserable', 'dejected', 'low',
                   'lower', 'lowest', 'fear', 'fears', 'feared', 'fearing', 'fearful', 'frightened', 'frightening',
                   'afraid scared', 'terrified', 'anxious', 'anxiety', 'fright', 'frightful', 'distress',
                   'distressed', 'panic', 'panicked', 'panicky', 'alarm', 'alarmed', 'anxieties', 'worry', 'worries',
                   'trouble', 'troubling', 'disturb', 'disturbs', 'disturbed', 'disturbing', 'worrier', 'coward',
                   'cowards', 'suicide', 'suicides', 'suicidal', 'fed up', 'sickened', 'revolted', 'apprehension',
                   'apprehensions', 'lazy', 'lazier', 'laziest', 'laziness', 'lethargic', 'despairing', 'hopeless',
                   'despondent', 'in despair', 'stress', 'stressed', 'stressful', 'tension', 'pathetic', 'pitiable',
                   'cruel', 'crueler', 'cruelest', 'cruelly', 'cruelty', 'crushed', 'die', 'dying', 'died', 'dies',
                   'death', 'lose', 'loses', 'losing', 'lost', 'loser', 'fail', 'fails', 'failed', 'failing',
                   'failure', 'fiasco', 'disappointment', 'letdown', 'botch', 'flop', 'lonely', 'lonelier',
                   'loneliest', 'lonesome', 'alone', 'abandoned ', 'guilt', 'guilty', 'guiltier', 'guiltiest', 'blame',
                   'blames', 'blamed', 'blaming', 'kill', 'killing', 'killed', 'kills', 'hate', 'hates', 'hated',
                   'hating', 'narcissism', 'alienation', 'antidepressants', 'trainwreck', 'train wreck', 'pathetic',
                   'revolting', 'frustrate', 'frustrated', 'frustrating', 'frustrates', 'cut', 'cutting', 'scar',
                   'scars', 'razor', 'razor blade', 'punish', 'punished', 'punishing', 'punishes', 'breakdown',
                   'trigger', 'unstable', 'relapse', 'relapsed']

sleep_family = ['ישנתי', 'ישנו', 'ישנה', 'וביישנית', 'ישנתי', 'הישנה', 'ישנו', 'שינה', 'אישן', 'ישנתי', 'לישון', 'ישנה',
                'הישן', 'הישנה', 'ולישון', 'מלישון', 'נירדמתי', 'נרדם', 'נרדמתי', 'ונרדמתי', 'נירדמת', 'מיטת', 'המיטה',
                'למיטה', 'במיטה', 'מהמיטה', 'שנצ', 'שנ"צ', 'שנץ']
sleep_family_en = ['sleep', 'sleeps', 'slept', 'sleeping', 'sleeper', 'sleepy', 'sleepier', 'sleepiest', 'fall asleep',
                   'asleep', 'go to sleep', 'went to sleep', 'fall asleep', 'fell asleep', 'bed', 'beds', 'went to bed',
                   'go to bed', 'nap', 'naps', 'napping', 'napped', 'snooze', 'doze', 'dozing', 'slumber']

sport_family = ['מירוץ', 'מרוץ', 'מרוצים', 'במרוץ', 'במירוץ', 'וריצה', 'רצו', 'רצה', 'ריצה', 'רצתי', 'שרציתי', 'לרוץ',
                'הלתכי', 'שהולכת', 'הולכת', 'תהליך', 'הלכאות', 'כשהלכתי', 'שהלכתי', 'והלך', 'ההליכה', 'הולך', 'הלכנו',
                'מהלך', 'והליכה', 'הולכות', 'שהולך', 'במהלך', 'הלכה', 'הולכים', 'הלכתי', 'והולכת', 'הלכו', 'שהלך',
                'והלכתי', 'להליכה', 'הלך', 'שהלכנו', 'הליכה', 'לספורט', 'והספורט', 'הספורט', 'ספורטאית', 'שספורט',
                'ספורטאי', 'וספורט', 'ספורט', 'כושר', 'הכושר', 'האימונים', 'להיתאמן', 'לאימונים', 'האימון', 'מתאמנת',
                'לאימון', 'אתאמן', 'אימון', 'להתאמן', 'במאמנת', 'שהאימונים']
sport_family_en = ['race', 'raced', 'racing', 'racer', 'run', 'runs', 'ran', 'running', 'runner', 'walk', 'walked',
                   'walking', 'walker', 'sport', 'exercise', 'sports', 'exercise', 'exercising', 'sportsman',
                   'sporting', 'fitness', 'calisthenics', 'gymnastics', 'workout', 'workouts', 'working out',
                   'work out', 'working out', 'train', 'trains', 'trained', 'training', 'practice', 'practiced',
                   'practicing', 'practicing']

thinness_family = ['רזון', 'לרזות', 'רזות', 'רזיתי', 'לרזה', 'רזה', 'שרזיתי', 'רזים', 'להרזות', 'שרזה', 'כשהרזון',
                   'ורזיתי', 'ולהרזות', 'שהרזתי', 'רזית', 'מרזים', 'רזונת', 'ההרזיה', 'מרזה', 'הרזייה', 'ותרזי',
                   'לרזון', 'הרזים', 'הרזון', 'רזתה', 'ורזה', 'דקיקה', 'דקה', 'דק', 'דקות', 'דקיקות', 'לדקה', 'מקל',
                   'עצמות הלחיים', 'עצמות האגן', 'עצמות בולטות', 'עצמות הבריח', 'עצם', 'העצמות', 'ועצמות', 'יבלוט',
                   'הבולטות', 'בלטו', 'בולטות', 'לבלוט', 'שבולט', 'בזוית', 'זוויותיות', 'זוויות', 'שדופות', 'שדוף',
                   'גוף', 'בטן', 'פנים', 'תחת', 'ראש', 'החזה', 'צלע', 'צלעות', 'הצלעות', 'עצמות', 'להרזות', 'דיאטה',
                   'דיאטנית', 'לרדת', 'להוריד', 'צמוד', 'צמודה', 'שצמוד', 'צמודד', 'צמודות', 'שטוחה', 'השטוחה']
thinness_family_en = ['thin', 'thinness', 'thinner', 'thinnest', 'gaunt', 'skinny', 'skinniness', 'skinnier  skinniest',
                      'slim', 'slimness', 'slimmer', 'slimmest', 'slender', 'slenderer', 'slenderest', 'emaciated',
                      'lose weight', 'losing weight', 'lost weight', 'slight', 'delicate', 'boney', 'bonier', 'boniest',
                      'bone', 'bones', 'skin and bones', 'body', 'bodies', 'stomach', 'sticking out', 'stick out',
                      'sticks out', 'stuck out', 'angular', 'rib', 'ribs', 'ribcage', 'hip', 'hips', 'hipbones', 'face',
                      'facial', 'chest', 'backside', 'rear', 'rear end', 'skeleton', 'tummy', 'undernourished',
                      'diet', 'diets', 'dieting', 'go on a diet', 'dietician', 'tight', 'tightest', 'flat', 'flatter',
                      'flattest', 'skeletal', 'lean', 'lanky', 'belly', 'butt', 'butts', 'ass', 'behind', 'waist',
                      'goal weight', 'GW', 'target', 'collar']

calories_family = ['הקלורי', 'קלוריות', 'קלוריה', 'הקלוריות', 'קלורי', "קל'", 'משקלתי', 'נשקלת', 'שמשקל', 'במשקל',
                   'להשקל', 'לשקול', 'נשקלתי', 'למשקלי', 'אשקול', 'והמשקל', 'בשקילה', 'ושוקלת', 'למישקל', 'שהמשקל',
                   'נישקלת', 'שקלו', 'ושקלו', 'נשקלים', 'ששוקלת', 'שקלתי', 'כששקלתי', 'משקל', 'ושקלה', 'ששקלתי',
                   'נישקלתי', 'המישקל', 'ממשקל', 'מששקלתי', 'במישקל', 'שקלה', 'אשקל', 'למשקל', 'שקילות', 'שוקלת',
                   'מהמשקל', 'שמקלה', 'המשקל', 'קילו', 'קילוו', 'בקילוגרמים', 'קילומטר', 'בקילו', 'ק"ג', 'בקילוגרמים',
                   'גרם']
calories_family_en = ['calorie', 'calories', 'caloric', 'weight', 'weigh', 'weighs', 'weighed', 'weighing', 'scale',
                      'pounds', 'kilos', 'ounces', 'scales', 'pound', 'ounce', 'gram', 'grams', 'ton', 'tons',
                      'weightless', 'measurements', 'metabolism', 'stone', 'stones', 'intake', 'gained', 'cals', 'bmi',
                      'lbs', 'kcals']

vulgarity_family = ['FUCT', 'FUCK', 'זין', 'בהמה', 'לעזאזל', 'לעזעזל', 'סמים', 'אלכוהול', 'מין', 'סקס', 'הזיוני',
                    'להזדיין', 'המזוין', 'זונה', 'סם', 'לסם', 'וסמים', 'והסמים', 'פאק', 'פאקינג', 'מפאקינג', 'כוסית',
                    'כוסיות', 'וכוסיות', 'לעשן', 'עישנתי', 'עישון', 'הסיגריה', 'סיגריות', 'וסיגריות', 'בסיגריות',
                    'הסיגריות', 'סיגריה', 'החרא', 'חראות', 'מהחרא', 'חרא', 'טיפש', 'מטופש', 'טיפשה', 'טיפשותי', 'מכוער',
                    'מכוערת', 'המכוערת', 'ומכוערת', '"המכוערת"', 'דפוק', 'דפוקה', 'דפוקים', 'איכסה', 'איכסוש', 'מגעיל',
                    'ומגעיל', 'המגעיל', 'מגעילה', 'ומגעילה', 'מגעילה!', 'מגעילה!!', 'המגעילים', 'התחרפנתי', 'התחרפנו',
                    'להתחרפן', 'מתחרפנת', 'שרמוטה', 'בזבל', 'שונאת', 'שונאים', 'שומאת', 'פסיכי', 'פסיכית', 'פסיכית!',
                    'לנשק', 'התנשקתי', 'לחבק', 'להתחבק', 'מחובקת', 'לשכב', 'ולשכב', 'לשדיים', 'סקס', 'סקסית', 'והסקס',
                    'ערומה']
vulgarity_family_en = ['fuck', 'fuck you', 'fucks', 'fucking', 'fucker', 'mother fucker', 'damn', 'hell', 'shit',
                       'curse', 'curses', 'cursed', 'cursing', 'curser', 'curse words', 'sex', 'lay', 'lays', 'laid',
                       'sleep with', 'sleeping with', 'slept with', 'sleep together', 'slept together',
                       'went to bed with', 'go to bed with', 'slut', 'sluts', 'alcohol', 'liquor', 'drinks', 'drinking',
                       'drinker', 'drunk', 'stoned', 'sexy', 'broad', 'cunt', 'smoke', 'smoked', 'smoking', 'smokes',
                       'smoker', 'cigarette', 'cigarettes', 'dumb', 'dummy', 'idiot', 'moron', 'imbecile', 'maniac',
                       'ugly', 'uglier', 'ugliest', 'disgusting', 'disgusting!', 'disgusting!!', ' revolting',
                       'turn off', '  lose it', 'losing it', 'lost it', 'garbage', 'piece of garbage', 'piece of shit',
                       'shitty', 'breasts', 'boobs', 'nipple', 'nipples', 'nips', 'crazy', 'psycho', 'nuts', 'naked',
                       'nude', 'undressed', 'pussy', 'shithead', 'asshole', 'bastard', 'son of a bitch', 'bitch', 'tit',
                       'tits', 'whore', 'dick', 'dick head', 'prick', 'crap', 'frigging', 'twat', 'xxx', 'stupid',
                       'dumb', 'suck', 'sucks', 'worthless', 'crackers', 'icky', 'ickier', 'ickiest', 'punish',
                       'punished', 'punishing', 'destroy', 'ugh', 'evil']

decreasing_family = ['0', 'אפס', '1', '2', 'קצת', 'לאט', 'בקושי', 'חוסר', 'דל', 'דלה', 'בלי', 'בקושי', 'גמד', 'טיפה',
                     'לא', 'לאו', 'מעט', 'סתם', 'עלוב', 'קטן', 'הקטן', 'קטנה', 'הקטנה', 'קטנטן', 'הקטנטן', 'רע', 'רק',
                     'לא מוצלח', 'לא מספיק', 'מעט מאוד', 'על הפנים', 'לא כל כך', 'חסר', 'חסרת', 'וחסרת', 'חסרות',
                     'אסור', 'אסור?', 'אסורים', 'שאסור', 'ואסור']
decreasing_family_en = ['0', 'zero', '1', '2', 'bit', 'a little', 'a bit', 'a tiny bit', 'hardly', 'hardly any', 'weak',
                        'poor', 'without', 'lacking', 'free', 'drop', 'drops', 'small', 'tiny', 'miserable',
                        'disgraceful', 'bad', 'worse', 'worst', 'but', 'unsuccessful', 'unsuccessfully', 'very little',
                        'no', 'not', 'neither', 'not enough', 'too tittle', 'missing', 'not so much', 'forbidden',
                        'not permitted', 'not permissible', 'not allowed', 'under', 'restrict', 'restricts',
                        'restricted', 'restricting', 'limit', 'limits', 'limited', 'limiting', 'barely', 'hardly',
                        'seldom', 'worthless', 'little', 'less', 'least', 'few', 'fewer', 'fewest', 'each', 'only',
                        'exclusively', 'just', 'sole', 'solely', 'never', 'rarely', 'seldomly', 'prohibited',
                        'outlawed', 'illegal', 'illicit']

increasing_family = ['ארוך', 'גאון', 'גדול', 'גם', 'די', 'דגול', 'המון', 'הצטיינות', 'הצלחה', 'הרבה', 'וואחד', 'חזק',
                     'חכם', 'חמוד', 'הכי טוב', 'חשוב מאוד', 'יפה מאוד', 'טוב מאוד', 'גדול מאוד', 'מאוד חשוב',
                     'ככל האפשר', 'מבסוט מאוד', 'ממש מדהים', 'סוף הדרך', 'חבל על הזמן', 'ענק', 'ענקית', 'מדהים',
                     'מדהימה', 'לא מעט', 'כ"כ', 'ככ', 'כלכך', 'מהר']
increasing_family_en = ['long', 'genius', 'geniuses', 'also', 'enough', 'prominent', 'famous', 'many', 'excellence',
                        'excellent', 'success', 'successful', 'strong', 'strength', 'best', 'the best', 'the very best',
                        'very important', 'important', 'large', 'larger', 'largest', 'big', 'bigger', 'biggest',
                        'stunning', 'as much as possible', 'very satisfied', 'fantastic', 'unbelievable', 'awesome',
                        'overwhelming', 'breathtaking', 'terrific', 'outstanding', 'superb', 'excellent', 'wonderful',
                        'superbly', 'wonderfully', 'fabulous', 'fabulously', 'magnificent', 'magnificently',
                        'tremendous', 'first-class', 'brilliant', 'superb', 'superbly', 'sensational tremendous',
                        'amazing', 'wonderful', 'astounding', 'great', 'greater', 'greatest', 'really great', 'giant',
                        'as much', 'so much', 'fast', 'faster', 'fastest', 'not a little', 'ultimate', 'absolute',
                        'absolutely', 'total', 'totally', 'fave', 'favorite', 'top', 'serious', 'seriously', 'real',
                        'really', 'actual', 'actually', 'honestly', 'much', 'most', 'many', 'both', 'several',
                        'completely', 'often']

sickness_family = ['חולה', 'החולה', 'וחולה', 'חולנית', 'מחלה', 'חולים', 'החולים', 'מחלה', 'ומחלה', 'והמחלה', 'רופא',
                   'הרופא', 'לרופא', 'והרופא', 'האחות', 'אישפזו', 'אישפוז', 'לאישפוז', 'מהאישפוז', 'במיון', 'למיון',
                   'פסיכאטר', 'פסיכאטרים', 'פסיכאטרי', 'בפסיכיאטרית', 'פסיכולוג', 'הפסיכולוג', 'פסיכולוגים',
                   'פסיכולוגי', 'פסיכולוגי?', 'בפסיכולוג', 'לפסיכולוג', 'לפסיכולוג!', 'לפסיכולוגית', 'הפסיכולוגית',
                   'והפסיכולוגית', 'שהפסיכולוגית', 'ניתוח', 'הניתוח', 'מהניתוח', 'והניתוח']
sickness_family_en = ['sick', 'sicker', 'sickest', 'ill', 'illness', 'disease', 'disorder', 'doctor', 'doctors',
                      'physician', 'physicians', 'nurse', 'nurses', 'nursing', 'hospital', 'hospitals',
                      'hospitalization', 'hospitalizations', 'emergency room', 'ER', 'trauma', 'trauma room',
                      'psychiatrist', 'psychiatrists', 'pills', 'pills', 'medication', 'medications', 'meds',
                      'medicine', 'icu', 'ward', 'messed', 'messed up', 'screwed', 'screwed up', 'disorder',
                      'disorders', 'desperate', 'desperately', 'desperation', 'obsess', 'obsessed', 'obsession',
                      'obsesses', 'worry', 'worries', 'worrying', 'frantic', 'psychiatric', 'psychologist',
                      'psychologists', 'psychology. psychological', 'psychologically', 'psychological?',
                      'psychologist!', 'operation', 'operations', 'procedure', 'procedures', 'exam', 'examination',
                      'therapist', 'counsellor', 'counselling']

love_family = ['אהבה', 'באהבה', 'כאהבה', 'לאהבה', 'האהבה', 'ואהבה', 'לאהוב', 'שאוהבים', 'נאהבת', 'אהבתי', 'אוהבת',
               'ואהבתי', 'ואוהבת', 'חום', 'חיבה', 'בחיבה', 'מחבבת', 'חום', 'בחום', 'חמימות', 'בחמימות']
love_family_en = ['love', 'loves', 'loved', 'loving', 'warmth', 'affection', 'fondness', 'care', 'cares', 'caring',
                  'cared', 'lovelies']

noun_family = ['woman', 'women', 'man', 'men', 'people', 'person', 'persons', 'male', 'males', 'female', 'females',
               'individual', 'individuals', 'party', 'parties', 'other', 'others', 'boy', 'boys', 'girl', 'girls',
               'fellow', 'fellows', 'guy', 'guys', 'gal', 'gals', 'one', "one's", 'one another', 'each other']

sex_family_en = ['sex', 'lay', 'lays', 'laid', 'sleep with', 'sleeping with', 'slept with', 'sleep together',
                 'slept together', 'went to bed with', 'go to bed with', 'slut', 'sluts', 'sexy', 'broad', 'cunt',
                 'breasts', 'boobs', 'nipple', 'nipples', 'nips', 'naked', 'nude', 'undressed', 'pussy', 'tit', 'tits',
                 'whore', 'dick', 'dick head', 'prick', 'action', 'boyfriend', 'boyfriend', 'bf']

cursing_family_en = ['fuck', 'fuck you', 'fucks', 'fucking', 'fucker', 'mother fucker', 'fuckton', 'damn', 'hell',
                     'shit', 'curse', 'curses', 'cursed', 'cursing', 'curser', 'curse words', 'dumb', 'dummy', 'idiot',
                     'moron', 'imbecile', 'maniac', 'ugly', 'uglier', 'ugliest', 'disgusting', 'disgusting!',
                     'disgusting!!', 'revolting', 'turn off', 'lose it', 'losing it', 'lost it', 'garbage',
                     'piece of garbage', 'piece of shit', 'shitty', 'shithead', 'asshole', 'bastard', 'son of a bitch',
                     'bitch', 'crap', 'frigging', 'twat', 'xxx', 'stupid', 'dumb', 'suck', 'sucks', 'worthless',
                     'crackers', 'icky', 'ickier', 'ickiest', 'crazy', 'psycho', 'nuts', 'destroy', 'ugh', 'evil',
                     'dumbass', 'goddammit', 'fat ass', 'fatass', 'selfish', 'dammit', 'piss', 'pissed', 'pissing',
                     'pisses', 'WTF', 'f-ck', 'f-cking', 'bull', 'bullshit', 'BS', 'idiotic', 'crappy']

alcohol_family_en = ['alcohol', 'liquor', 'drinks', 'drinking', 'drinker', 'drunk', 'stoned', 'wasted']

smoke_family_en = ['smoke', 'smoked', 'smoking', 'smokes', 'smoker', 'cigarette', 'cigarettes', 'cigs']

export_50_terms_he = ['גוף', 'ריסון', 'משקל', 'פחד', 'משלשלים', 'ספורט', 'קלוריות', 'ויתור', 'כישלון', 'הקאה', 'מצוקה',
                      'אסלה', 'בהמה', 'בולמוס', 'צמתי', 'תסכול', 'לרדת במשקל', 'התקף חרדה', 'הרעבה', 'תפריט',
                      'דיאטנית', 'אנה', 'מענישה', 'אוכל', 'פרו אנה', 'דימוי גוף', 'שליטה', 'גשמי', 'טוהר', 'קטן',
                      'למות', 'אנורקסיה', 'תת משקל', 'כמויות', 'טכניקות', 'בליסה', 'רזה', 'רזון', 'שטוחה', 'בולטות',
                      'זוויתית', 'עצמות', 'ידחפו', 'להקיא', 'גרון', 'פיתוי', 'בולסת', 'עצמות בריח', 'עודף', 'דיאטה']
export_50_terms_en = ['pro-ana', 'fasting', 'starve', 'to punish', 'strong', 'meal plan', 'ana-food', 'relapse',
                      'recover',
                      'worthless', 'valid', 'jealous', 'GW', 'UGW', 'pain', 'doubt', 'crashing', 'tube', 'depressed',
                      'intake',
                      'gained', 'force', 'dietician', 'consumed', 'cut', 'hipbones', 'boney', 'waist', 'puke', 'ed',
                      'unit', 'scale',
                      'tight', 'desire', 'crunches', 'caved', 'disgusting', 'full', 'fade', 'stashed', 'resist',
                      'triggering',
                      'temptation', 'binged', 'exercise', 'restricting', 'mess', 'gluttony', 'cope', 'obsession']
export_50_terms_trans_he = ['פרו-אנה', 'צום', 'מרעב', 'להעניש', 'חזק', 'תוכנית ארוחות', 'אנה-אוכל', 'הישנות', 'להחלים',
                            'חסר ערך',
                            'תקף', 'מקנא', 'משקל מטרה', 'משקל יעד סופי', 'כאב', 'ספק', 'מתרסק', 'צינור', 'מדוכא',
                            'צריכת', 'צבר',
                            'כוח', 'דיאטנית', 'נצרך', 'חתך', 'עצמות ירך', 'בוני', 'מותן', 'פוק', 'אד', 'יחידה', 'סולם',
                            'הדוק',
                            'תשוקה', 'כפיפות בטן', 'מרווח', 'מגעיל', 'מלא', 'דוהה', 'מנותק', 'מתנגד', 'מפעיל', 'פיתוי',
                            'מקושטש',
                            'תרגיל', 'מגביל', 'בלגן', 'גרגרנות', 'להתמודד', 'אובססיה']
export_50_terms_trans_en = ['body', 'restraint', 'weight', 'fear', 'laxatives', 'sport', 'calories', 'concession',
                            'failure ', 'vomiting ',
                            'distress', 'toilet bowl', 'animal', 'binge', 'i was fasting', 'frustration ',
                            'lose weight', 'panic attack',
                            'starving', 'menu', 'dietician', 'anna', 'punishable', 'food', 'pro anna', 'body image',
                            'control',
                            'materialistic ', 'purity', 'small', 'die', 'anorexia ', 'underweight', 'quantity',
                            'technique', 'gluttony',
                            'thin', 'thinness', 'flat', 'sticking out', 'angular', 'bones', 'will push', 'vomit',
                            'throat', 'temptation',
                            'to overeat', 'collarbones', 'over', 'diet']

top_500 = ['10', '30', 'ADIDAS', 'אבא', 'אבל', 'אדם', 'אהבתי', 'אהיה', 'או', 'אוהבת', 'אוכל', 'אוכלת', 'אולי', 'אומר',
           'אומרים', 'אומרת', 'אוף', 'אותה', 'אותו', 'אותי', 'אותך', 'אותם', 'אז', 'אחד', 'אחוז', 'אחר', 'אחרי',
           'אחרים', 'אחרת', 'אחת', 'אי', 'איזה', 'איך', 'אין', 'איתה', 'איתו', 'איתי', 'אך', 'אכילה', 'אכלתי', 'אכפת',
           'אל', 'אלא', 'אליו', 'אם', 'אמא', 'אמר', 'אמרה', 'אמרו', 'אמרתי', 'אנה', 'אנורקסיה', 'אנורקסית', 'אנחנו',
           'אני', 'אנשים', 'אף', 'אפילו', 'אפשר', 'אצל', 'את', 'אתה', 'אתם', 'אתמול', 'בא', 'באופן', 'באמת', 'בבוקר',
           'בבית', 'בבקשה', 'בגדים', 'בגוף', 'בגלל', 'בדיוק', 'בדרך', 'בה', 'בהם', 'בהתחלה', 'בו', 'בוקר', 'בזה',
           'בזמן', 'בחדר', 'בחזרה', 'בחיים', 'בטוחה', 'בטח', 'בי', 'ביום', 'ביותר', 'בין', 'בכל', 'בכלל', 'בלי',
           'בלילה', 'במיוחד', 'במקום', 'במראה', 'במשך', 'במשקל', 'בן', 'בנות', 'בסדר', 'בסוף', 'בעולם', 'בעיה', 'בעיקר',
           'בעצם', 'בעצמי', 'בערב', 'בערך', 'בפעם', 'בצורה', 'בקיצור', 'בראש', 'ברגע', 'בריא', 'בריאה', 'בשבוע',
           'בשביל', 'בת', 'בתוך', 'גדול', 'גדולה', 'גוף', 'גם', 'דבר', 'דברים', 'די', 'דיאטה', 'דיאטות', 'דיאטת', 'דרך',
           'האוכל', 'האחרונה', 'האלה', 'האם', 'האמת', 'האנשים', 'הבא', 'הבטן', 'הביתה', 'הבלוג', 'הבנתי', 'הגוף',
           'הגיע', 'הגעתי', 'הדבר', 'הדברים', 'הדיאטה', 'הדרך', 'הוא', 'הולכת', 'הזאת', 'הזה', 'הזו', 'הזמן', 'החיים',
           'החלטתי', 'היא', 'היה', 'היו', 'היום', 'הייתה', 'הייתי', 'היתה', 'היתי', 'הכי', 'הכל', 'הלכתי', 'הם', 'המון',
           'המצב', 'המשקל', 'הן', 'הספר', 'העולם', 'הפעם', 'הפרעות', 'הצלחתי', 'הראשון', 'הרבה', 'הרגשתי', 'הרי',
           'השבוע', 'השנה', 'התחיל', 'התחלתי', 'ואז', 'ואיך', 'ואין', 'ואם', 'ואני', 'ואפילו', 'ואת', 'וגם', 'והוא',
           'והיא', 'והם', 'וזה', 'וחצי', 'ויש', 'וכל', 'וכמה', 'ולא', 'ומה', 'ועוד', 'ועכשיו', 'ועל', 'ורק', 'זאת',
           'זה', 'זהו', 'זו', 'זוכרת', 'זמן', 'חברה', 'חברות', 'חברים', 'חדש', 'חדשה', 'חודש', 'חודשיים', 'חוזרת',
           'חולה', 'חולים', 'חוץ', 'חושבת', 'חזק', 'חזרתי', 'חחח', 'חייבת', 'חיים', 'חלק', 'חצי', 'חשבתי', 'חשוב',
           'טוב', 'טובה', 'טיפה', 'ידעתי', 'יהיה', 'יהיו', 'יודע', 'יודעים', 'יודעת', 'יום', 'יותר', 'יחד', 'יכול',
           'יכולה', 'יכולתי', 'ילדה', 'ילדים', 'ים', 'ימים', 'יפה', 'ירדתי', 'ירקות', 'יש', 'כאילו', 'כאלה', 'כאן',
           'כבר', 'כדי', 'כוח', 'כול', 'כולם', 'כושר', 'כזאת', 'כזה', 'כי', 'כיף', 'כך', 'ככה', 'כל', 'כלום', 'כלכך',
           'כמה', 'כמו', 'כמובן', 'כמעט', 'כן', 'כנראה', 'כסף', 'כרגע', 'כשאני', 'לא', 'לאחר', 'לאט', 'לאכול', 'לאמא',
           'לאנשים', 'לב', 'לבד', 'לבית', 'לבכות', 'לבנות', 'לגמרי', 'לדבר', 'לה', 'להבין', 'להגיד', 'להגיע', 'להוריד',
           'להיות', 'להם', 'להמשיך', 'להפסיק', 'להקיא', 'להרגיש', 'להרזות', 'להתחיל', 'לו', 'לזה', 'לחזור', 'לחיות',
           'לחשוב', 'לי', 'לישון', 'לך', 'לכך', 'לכל', 'לכם', 'לכתוב', 'ללא', 'ללכת', 'למה', 'למות', 'למצוא', 'למרות',
           'לנו', 'לנסות', 'לעבור', 'לעצמי', 'לעשות', 'לפחות', 'לפני', 'לפעמים', 'לצאת', 'לקבל', 'לקחת', 'לראות',
           'לרדת', 'לשמור', 'לתת', 'מאוד', 'מאז', 'מאיפה', 'מאמינה', 'מבינה', 'מגיע', 'מדי', 'מה', 'מהבית', 'מהם',
           'מהר', 'מוגלר', 'מול', 'מזה', 'מחדש', 'מחיר', 'מחר', 'מי', 'מידי', 'מים', 'מישהו', 'מישהי', 'מכוערת', 'מכל',
           'מלא', 'ממנו', 'ממני', 'ממש', 'מנסה', 'מסוגלת', 'מספיק', 'מעט', 'מפחדת', 'מצאתי', 'מצליחה', 'מקווה', 'מקום',
           'מקרה', 'מרגישה', 'משהו', 'משנה', 'משקל', 'מתה', 'מתוך', 'מתחילה', 'מתי', 'נורא', 'ניסיתי', 'נכון', 'נמאס',
           'נס', 'נראה', 'סוף', 'סיבה', 'ספורט', 'סתם', 'עבודה', 'עד', 'עדיין', 'עוד', 'עודף', 'עושה', 'עושים', 'עכשיו',
           'על', 'עלי', 'עליה', 'עליהם', 'עליו', 'עליי', 'עם', 'עצמי', 'ערב', 'עשיתי', 'פה', 'פחות', 'פעם', 'פעמים',
           'פרה', 'פרו', 'פשוט', 'פתאום', 'צהריים', 'צריך', 'צריכה', 'קורה', 'קטן', 'קטנה', 'קילו', 'קל', 'קלוריות',
           'קפה', 'קצת', 'קרה', 'קשה', 'ראיתי', 'רגע', 'רואה', 'רואים', 'רוצה', 'רזה', 'רע', 'רעבה', 'רצה', 'רציתי',
           'רק', 'שאין', 'שאכלתי', 'שאם', 'שאנחנו', 'שאני', 'שאת', 'שאתה', 'שאתם', 'שבוע', 'שגם', 'שהוא', 'שהיא',
           'שהיה', 'שהייתי', 'שהם', 'שוב', 'שווה', 'שום', 'שומן', 'שונאת', 'שונה', 'שוקלת', 'שזה', 'שיהיה', 'שיש',
           'שישי', 'שכל', 'של', 'שלא', 'שלה', 'שלהם', 'שלו', 'שלוש', 'שלי', 'שלך', 'שלכם', 'שלנו', 'שם', 'שמן', 'שמנה',
           'שנה', 'שני', 'שנים', 'שעה', 'שעות', 'שצריך', 'תזונה', 'תמיד']

custom_list = ['נימאס', 'ככ', 'בלה', 'ממך', 'הולדת', 'אחי', 'זירו', 'שמלה', '100', '200', 'חרא', 'ילדות', 'מחיר',
               'כדורים', 'ביניים', 'דמעות', 'אכתוב', 'בחלום', 'נוראי', 'דיאט', 'אני', 'היתי', 'הנאה', 'ניראת', 'כף',
               'לקראת', 'יקר', 'סביב', 'חג', 'ארד', 'פיתה', 'ישנה', 'פרה', 'ומשמינה', 'האסלה', 'מכנסיים', 'תן', 'לא',
               'סבבי', 'מאיפה', 'bmi', 'יומן', 'שיעור', 'בשישי', 'השם', 'קציצות', 'הג', 'חמוד', 'שנאתי', 'פתחתי',
               'תמונה', 'התחושה', 'שמא', 'חתיכת', 'שבע', 'בחודש', 'לימודים', 'בשר', 'שהבלוג', 'כאבי', 'בנתיים', 'אכפת',
               'פיצה', 'סכין', '75', 'דיאטת', 'תאכלי', 'נשקלתי', 'אצטרך', 'האווירה', 'ינס', '11', 'העצמי', 'עצמות',
               'הפרעת', 'כדור', 'מתוכנן', 'תת', 'רוח', 'ובלה', '48', 'הופך', 'שעברתי', 'אשכרה', 'התת', 'מלפפון', 'צעד',
               'הכוח', 'רעב', 'אלך', 'למישהו', 'חחח', 'פעמיים', 'בבצפר', 'והייתי', 'שתרצה', 'קג', '45', 'סוכרזית',
               'שליש', 'שאצליח', 'שלום', 'מתחילים', 'המגעיל', 'במרכז', 'מופתעת', 'השנה', 'רצתי', 'כשהיא', 'אתה', 'כלכך',
               'חזה', 'נגד', 'מזכיר', 'לשון', 'סתומה', '300', 'מרזה', '55', 'שיר', 'והמשקל', 'שנראה', 'השמנה', 'מחלה',
               'למדתי', 'לשבוע', 'אלייך', 'טונה', '58', 'מינוס', 'טיפים', 'רביעי', 'הרופא', 'קיבלתי', 'איפה', 'בכמה',
               'be', 'להרשות', 'ובסוף', 'ראש', 'וקצת', 'אתכם', 'משו', 'ולראות', 'ללב', 'יעד', 'מוכן', 'טובים', 'בתת',
               'ומחר', 'וואו', 'מורידה', 'לי', 'אתם', 'כיתה', 'הקאתי', 'חלבונים', 'הסרט', 'סה', 'נגיד', 'לשירותים',
               'למוות', 'הא', 'להיום', 'קר', 'שיער', 'מחיי', 'בדברים', 'תגידו', 'את', 'עברו', 'ליטר', 'מעניין', 'מילא',
               'וחסרת', 'אראה', 'מילה', 'סיגריות', 'המציאות', 'ולקחת', 'שלכם', 'כאב', 'שאלתי', 'שעוד', 'בחופש', 'מעדן',
               'רחוקה', 'forever', 'טחינה', 'מכוערת', 'עייפה', 'סליחה', 'גיליתי', 'שמח', 'כועסת', 'בשבילו', 'לשקול',
               'תלוי', 'בחודשים', 'ובין', 'שטחי', 'ואהבה', 'חדשים', 'אוי', 'פעילות', 'גרנולה', 'קשור', 'ימי', 'ברוקולי',
               'קולה', 'יורדת', 'מגעילה', 'בלב', 'אישה', 'מדהים', 'שאהיה', 'שימו', 'הצום', 'לאן', 'ריצה', '35', 'מרעב',
               'מסיבת', 'צלקות', 'הארוחת', 'שאת', 'לחץ', 'מתוקים', 'נחשב', 'חור', 'ישיבה', 'בקרוב', 'אפסיק', 'לנשום',
               'בספורט', 'להחמיר', 'טוסט', 'בכושר', 'נשברתי', 'קלוריות', 'אכילה', 'הפרעות', 'מתגעגעת', 'הילדה', 'אשר',
               'כוסית', 'להכיר', 'נוסעת', 'בחוץ', 'יאללה', 'שיכורה', 'והכל', 'הכושר', 'להתעסק', 'מזמינים', 'המכנס',
               'כלבה', '500', 'לבחור', 'לפתח', 'משלשל', 'לגיל', 'היחידי', 'תעלה', 'להפסיק', 'הפעם', 'זוכרת', 'גאה',
               'חיוך', 'אגיד', 'התפריט', 'ליפול', 'אבא', 'הקרוב', 'למעשה', 'ל50', 'חם', 'ברמות', 'שנת', 'שרשמתי',
               'הגובה', 'האף', 'כוס', 'ועדיין', 'כסף', 'מחכה', 'רעבים', 'וכשאני', 'משמינים', 'שרוצה', 'קוטג', 'בעלי',
               'מהחלון', 'לנגן', 'עיניים', 'שקילה', 'משקל', 'אנה', 'בבקשה', 'איתה', 'תה', 'בצבא', 'ביי', 'היפה',
               'שמנות', 'שלעולם', 'ברחוב', 'מנסים', 'לרשום', '28', 'ינסים', 'שלפעמים', 'הים', 'בוקר', 'למצב', 'פאק',
               'ההוא', 'חוויות', 'מעדיפה', 'יומי', 'רבה', 'בריאות', 'xd', 'להימנע', 'מנהלת', 'שילוב', '40', 'וכרגע',
               'השמנות', 'עליכם', 'זה', 'שנים', 'עודף', 'גרם', 'מצד', 'חח', 'משם', 'בעבודה', 'רחוק', 'נופלת', 'מניחה',
               'איי', 'אסיים', '90', 'מתי', 'נחמד', 'והם', 'ויום', 'במישקל', 'ואופן', 'פרו', 'מסוגלת', 'שבועיים',
               'לבכות', 'אליי', 'השיחה', 'בגד', 'השומנים', 'לכלום', 'נפוחה', 'רחמים', 'הריקנות', 'לחברים', 'יעזור',
               'להגביל', 'המוח', 'ואתה', 'טלפון', 'שעליתי', 'נאבקת', 'ספורט', 'חולה', 'סלט', 'כתבתי', 'אחוז', 'אה',
               '24', 'בהמה', 'ואסור', 'מבט', 'ופחות', 'יורד', 'כאסח', 'צמתי', 'נשאר', 'חביתה', 'ידוע', 'השינויים',
               'מהצבא', 'אימא', 'תראי', 'הנה', 'ושוב', 'בולמוסים', 'אמנם', 'רגעים', 'עובר', 'להסתובב', 'המחלה', 'מוזרה',
               'שולטת', 'בשיעור', 'הדוגמנות', 'שאיתי', 'החלפתי', 'נקווה', 'מינימום', 'להרזיה', 'רגשות', 'לכתוב', 'האם',
               'נגמר', 'לקחתי', 'שעבר', 'השעה', 'מזמן', 'קבוע', 'נעלם', 'מסת', 'שאר', 'מלאות', 'בבסיס', 'ייתכן',
               'הכדורים', 'מהאשפוז', 'לעקוב', 'שומרת', 'רזית', 'שמנה', 'אנחנו', 'הולך', 'אותנו', 'שותה', 'עזבו',
               'יכלתי', 'לנצח', 'לומדת', 'משפט', 'שש', 'הקרובים', 'המלחמה', 'מקרוב', 'ישבנו', 'מידת', 'לך', 'סוף',
               'אוף', 'ההורים', 'פנים', 'תודה', 'שאף', 'ירוק', 'הרצפה', 'דק', 'לעצמך', 'רבות', 'שלושת', 'מכתב',
               'עובדים', 'להכין', 'ושמנה', 'קילו', 'חברה', 'ערב', 'המטרה', 'חולים', 'יושבת', 'דיאטנית', 'הלילה', 'כללי',
               'גבינה', 'להראות', 'רב', 'בימים', 'לדחוף', 'פירות', 'שהמשקל', 'צמה', 'לתכנן', 'מבלי', 'הרגשת', 'הזוי',
               'להתחבר', 'מעפנה', 'נראתה', 'המראה', 'הנכונה', 'שאתה', 'לעבור', 'עליהן', 'צריכים', 'הליכה', 'מדוע',
               'שניסיתי', 'הספקתי', 'שהן', 'למעגל', 'ברגל', 'מהגוף', 'טעות', 'אוקיי', 'שחשבתי', 'בגוף', 'נס', 'לוותר',
               'אעשה', '30', 'מקבל', 'ישר', 'האנורקסיה', 'שאלה', 'עמוק', 'עברתי', 'להתאמן', 'השרירים', 'העיקר', 'החוצה',
               'מטומטמת', 'זוג', 'עלייה', 'ואתם', 'להסביר', 'שיגידו', 'מעבר', 'לחפור', 'ההבנה', 'ויצאתי', 'שניים',
               'חיפשתי', 'עשרה', 'והצלחתי', 'בתקופה', 'האישי', 'חלק', 'סוכר', 'יעשה', 'שווה', 'עומדת', 'טיפשה', 'לחם',
               'העצמות', 'בנאדם', 'ממחר', 'אפשרי', 'והיו', 'פוחדת', 'למטה', 'לדיאטנית', 'אחותי', 'השראה', 'מאוכל',
               'רציני', 'באיזה', 'צדדים', 'בסביבות', 'בג', 'מערכות', 'שהרגשתי', 'נקי', 'ההגנה', 'צומות', 'עליך',
               'אוכלת', 'מלא', 'במראה', 'כנראה', 'גוף', 'חלב', 'שלושה', 'במשך', 'בפנים', 'אומנם', 'הורדתי', 'בהחלט',
               'ועד', 'שירות', 'נכונה', 'להזכיר', 'מכוער', 'הרזון', 'שואלים', 'מכולם', 'וואי', 'נכונים', 'גברים', 'היא',
               'אותך', 'מידי', 'ידעתי', 'לאהוב', 'אסור', 'מוכנה', 'אהבה', 'הלוואי', 'אופן', 'אצליח', 'עוגה', 'ניתן',
               'אלוהים', 'מדברת', 'שהתחלתי', 'הבאה', 'העיניים', '21', 'לעצור', 'תירוץ', 'שאלו', 'נראת', 'התגברתי',
               'תגובות', 'שטוחה', 'ארוכים', 'הפחמימות', 'מצפה', 'עגבניה', 'בעיקרון', 'הבולמוס', 'הבחורה', 'לשיחה',
               'במשקל', 'מגיע', 'חזקה', 'בולמוס', 'מידה', 'סיבה', 'ארוחת', 'אורז', 'המשפחה', 'וספורט', '42', 'המידה',
               'בעיניי', 'לובשת', 'כפית', 'בעיר', 'יוגורט', 'סיפרתי', 'יגרום', 'הרופאה', 'משלי', 'שלו', 'בעצמי', 'דיי',
               'אומר', 'הרגשתי', 'לאט', 'מלאה', 'יחסית', 'אותן', 'שאתם', 'התשובה', 'האכילה', 'הבוקר', 'מהחיים',
               'השמנתי', 'מקיאה', 'למחרת', 'טיפול', 'לצום', 'ארוכה', 'מתוק', 'עובדת', 'בפועל', 'מאות', 'ונכון', 'just',
               'האהובים', 'שכדאי', 'מרעיבה', 'להישבר', 'החומר', 'בבלוגים', 'רזים', 'שאני', 'אכלתי', 'יפה', 'וחצי',
               'להקיא', 'דם', 'הספר', 'כושר', 'עבר', 'למשקל', 'עדיף', 'אך', 'אנורקסית', 'להשאר', 'וכמובן', 'נמצא',
               'לעשן', 'הלאה', 'כוסות', 'היית', 'מוצאת', 'המכנסיים', 'נעשה', 'תנסו', 'הנ', 'שמשהו', 'ברגעים', 'שיום',
               'השירותים', 'לפוסט', 'מכך', 'בטלפון', 'אוהבת', 'שעות', 'כרגע', 'יכולתי', 'אלה', 'האחרונים', 'שמן',
               'מרגיש', 'וכן', 'ללבוש', 'מדהימה', 'המחשבות', 'בשנה', 'לספר', 'לשכוח', 'חסרת', 'להורים', 'חטיף', 'שניה',
               '43', 'בשלב', 'לשומן', 'מושלמת', '80', 'הפך', 'מזיק', 'העיינים', 'סרטים', 'מרגיע', 'מצטערת', 'שואפת',
               'לאכול', 'כיף', 'טיפה', 'לילה', 'רגילה', 'שטויות', 'הסוף', 'השומן', 'נמצאת', 'ארוחה', 'שאלות', 'במיטה',
               'מבטיחה', 'יחזור', 'כאשר', 'מבאס', 'שרוצים', 'בעיני', 'כשיש', 'נמוך', 'גרה', 'שקרה', 'גדולות', 'גבר',
               'פחמימות', 'בשוק', 'חיבוק', 'לבקש', 'לחרוג', 'במקביל', 'חום', 'לחבר', 'והרגשתי', 'שורף', 'בינינו',
               'כשראיתי', 'שאוכלים', 'גזרה', 'ומה', 'להסתכל', 'אהבתי', 'להרזות', 'בקיצור', 'אחזור', 'אלי', 'לשם', 'אצא',
               'כולל', 'יאכל', 'יגיע', 'שרציתי', 'שאנשים', 'נו', 'לעצמו', 'התחילו', 'להחזיק', 'החברה', 'שיגיע',
               'להשתדל', 'שאפילו', 'לתאר', 'מהעבודה', 'שאומרים', 'העיקרית', 'גופנית', 'כפות', 'הערב', 'שלישי', 'לחלום',
               'שנקראת', 'מהחדר', 'בהמתי', 'יוכל', 'ברצף', 'שלי', 'המון', 'לצאת', 'שלך', 'רעבה', 'בגדים', 'בהם',
               'לשמור', 'חודשים', 'סוג', 'מחפשת', 'תזונה', 'שוקולד', 'מהכל', 'יוצא', 'חוסר', '16', '49', '13', 'פיזית',
               'נוח', 'באנורקסיה', 'הרצון', 'ומגעילה', 'ערך', 'עוזר', 'שחשוב', 'מתסכל', 'להישקל', 'להחלים', 'בישראל',
               'להשתמש', 'מקבלת', 'נאיבית', '1000', 'ספר', 'עוף', 'בתחום', 'לתפריט', 'העלתי', 'הגב', 'יגידו', 'הגוף',
               'באופן', 'כזאת', 'זהו', 'יודעים', 'לאחר', 'מקרה', 'בלילה', 'שהיום', 'להן', 'ובלי', 'שמי', 'לעזור',
               'תפריט', 'שומעת', 'לשאול', 'בכיתה', 'לעמוד', 'החבר', 'להנות', 'להיכנס', '51', 'להשיג', 'שבא', 'מיוחד',
               'להביא', 'ושזה', 'אופנה', '62', 'מהמטרה', 'מכין', 'מדיי', 'ובטן', 'ואומרת', 'רוצה', 'המשקל', 'שונאת',
               'משנה', 'ואכלתי', 'מגיעה', 'אתחיל', 'עצמך', 'בשום', 'דקות', 'כותבת', 'שכתבתי', 'העבודה', 'עובד', 'הימים',
               'ובעיקר', 'כלומר', 'שבה', 'מצוין', 'נהדר', 'מיום', 'פרוסה', 'אימון', 'בשנתיים', 'מלאים', 'היינו',
               'מחשבות', 'הפה', 'נהנית', 'רגשית', 'בכלום', 'מסוגלים', 'אז', 'צהריים', 'הביתה', 'בנות', 'לקחת', 'נמאס',
               'אי', 'שאנחנו', 'בהצלחה', 'חבל', 'מיני', 'גורם', 'שנתיים', 'לגרום', 'ואתמול', '19', '400', 'אחרות',
               'הסבל', 'קורא', '14', 'אומץ', 'מסבירה', 'מולי', 'ונראה', 'כיום', 'דוגמנית', 'שהרבה', 'המערכת', 'הרגע',
               'רזה', 'שם', 'די', 'בא', 'איתו', 'מעצמי', 'ארוחות', 'יקרה', '60', 'בידיים', 'רבים', 'שבת', 'וכבר', 'מטר',
               'כשאין', '18', 'בארץ', 'חמישי', 'הנושא', 'מבין', 'שמישהו', 'אפשרות', 'הכרתי', 'תמונות', 'אורח', 'שקניתי',
               'להרעיב', 'מכם', 'והאמת', 'ובטח', 'בשעה', 'לאבד', 'והולכת', 'כולכם', 'מגיעים', 'השיער', 'מקל', 'אחורה',
               'לאנשים', 'לעלות', 'חושבים', 'בבטן', 'ביחד', 'שינוי', 'יצאתי', 'וכו', 'ידי', 'שתמיד', 'ופתאום', 'טעם',
               'לבלוג', 'לכן', 'עניין', 'חיצוני', 'מעלה', 'דקה', 'לאחרונה', 'חוזרים', 'תוכלו', 'רזון', 'קורנפלקס',
               'לשבת', 'שהחיים', 'התחלה', 'הרגיש', 'מכיר', 'בסופר', 'נהנת', 'תכננתי', 'נתון', 'שיפור', 'יקרות',
               'מאוכזב', 'מקבלים', 'בהכרח', 'והדבר', 'על', 'אהיה', 'השבוע', 'אמר', 'למות', 'אומרים', 'דיאטות', 'המצב',
               'הדרך', 'הדיאטה', 'הגדול', 'היחידה', 'איתם', 'באמצע', 'הבטחתי', 'לבנות', 'הראש', 'ההרגשה', 'עצובה',
               'מספר', 'ושתיתי', 'לאיזה', 'גיל', 'מפגר', 'כשהם', '34', 'כשהייתי', 'מהתפריט', 'החברים', 'תשובות', 'נתן',
               'בר', 'כמוהה', 'פני', 'מאנשים', 'כתוב', 'בורקסים', 'לצערי', 'מבית', 'כנה', 'רעיון', 'בננה', 'נטייה',
               'כך', 'לו', 'דיאטה', 'בריא', 'שומן', 'לחיות', 'במצב', 'בעיקר', 'מפחיד', 'לרזות', 'עבודה', 'עליתי',
               'גרוע', 'אוהבים', 'לחיים', 'צום', 'שואלת', 'לפי', 'פרוסות', '56', 'טריגר', 'תוכנית', 'סביבי', 'לבחורה',
               'רבע', 'מודה', 'מסתבר', 'הולכים', 'לחתוך', 'לדלג', 'בואי', 'לרופא', 'קמה', '65', 'גלידה', 'מיותרת',
               'נזכרת', 'נתנה', 'השריר', 'מרגישה', 'סתם', 'ימים', 'מאז', 'אמא', 'חיים', 'אלא', 'להוריד', 'יכולים',
               'מרוצה', 'היי', 'יראה', 'לדעת', 'ממה', 'והיום', 'לגוף', 'חופש', 'אליה', 'קמתי', 'עשה', 'עצמה', 'שהייתה',
               'איזו', 'וקשה', 'והרבה', 'מאושרת', 'נתתי', 'מדבר', 'חשובים', 'מרגישים', 'מתוסכלת', 'לעוד', 'מחבר',
               'נורמלי', 'באחת', 'בדיקת', 'שאי', 'שחזרתי', 'הטלוויזיה', 'התוצאה', 'לחבק', 'הזאת', 'צריך', 'בסדר', 'מחר',
               'בערך', 'עשיתי', 'מבינה', 'האחרון', 'שמחה', 'ילדים', 'רע', 'נראית', 'עושים', 'בטן', 'אמרה', 'היתה',
               'מגעיל', 'תפוח', 'שעובר', 'יפות', 'טובות', 'הגדולה', 'לשנות', 'לבוא', 'סיימתי', 'בכיתי', 'משפחה',
               'ירידה', 'הידיים', 'מאוכזבת', 'פרק', 'שלהן', 'לשים', 'הלא', 'שקשור', 'חלש', 'ידיים', 'הכתף', '59',
               'נפגשתי', 'לעצמכם', 'סיפורים', 'שלחו', 'קלים', 'בממוצע', 'אבל', 'בשביל', 'מקווה', 'מפחדת', 'כוח', 'מנסה',
               'ויש', 'קל', 'חברים', 'יומיים', 'חדש', 'למצוא', 'בחדר', 'קניתי', 'חסר', 'במילים', 'אהה', 'הצלחה', 'ריק',
               'שואל', 'לרצות', 'בתקווה', 'אנד', 'תואר', '22', 'אמיתית', 'שמוריד', 'מייאש', 'שקיים', 'תל', 'כל', 'אותי',
               'הוא', 'הכי', 'ואז', 'מזה', 'הזמן', 'לכם', 'הן', 'אנורקסיה', 'הרי', 'מהבית', 'חזק', 'שמעתי', 'הפוסט',
               'פוסט', 'משתדלת', 'שרק', 'שבהם', 'בסך', 'ואף', 'הבית', 'נשים', 'המילים', 'רזיתי', 'ספק', 'ולפעמים',
               'סבבה', 'מיד', 'השיר', 'מבחינת', 'ביס', 'התזונה', 'שתבינו', 'הבריאות', 'יקח', 'הדיאטות', 'הטיפול',
               'שמצאתי', 'קשורים', 'הפיזי', 'יגמר', 'באיך', 'המשכתי', 'נפל', 'מצבים', 'נגמרת', 'לפחד', 'של', 'מאוד',
               'אוכל', 'הם', 'נורא', 'מישהו', 'להם', 'שום', 'מים', 'הדברים', 'שלה', 'מחדש', '50', 'בפעם', 'בעוד', 'יחד',
               'אשמח', 'היעד', 'להאמין', 'מנת', 'החלק', 'חמש', 'למי', 'לאף', 'בטירוף', 'המחשבה', 'דוחה', 'לדעתי',
               'עבודות', 'לימים', 'שעברה', 'בטוחים', 'יכולות', 'הסתכלתי', 'הקשה', 'משתנה', 'כואבת', 'עבד', 'ממליצה',
               'שרואים', 'דעת', 'חדשות', 'שוב', 'כלום', 'מי', 'לרדת', 'אף', 'כשאני', 'לנו', 'לחזור', 'ילדה', 'חשוב',
               'כאן', 'חשבתי', 'ברגע', 'בצורה', 'ראיתי', 'קטנה', 'שצריך', 'רואים', 'ואיך', 'שתיתי', 'תהיה', 'במיוחד',
               'היחיד', 'מסתכלת', 'בצהריים', 'בחורה', 'שבועות', 'מאד', 'תהליך', 'נושא', 'נותן', 'שאחרי', 'מוטיבציה',
               'ואחר', 'בנוסף', 'דירה', 'שנשאר', 'חברת', 'יבוא', 'דרכים', 'העניין', 'עבור', 'מבפנים', 'המחזור', 'למען',
               'וממש', 'מסביב', 'במחשב', 'באינטרנט', 'בבום', 'וראיתי', 'אישי', 'למדי', 'מרשה', 'פיתוי', 'מהעובדה', 'עם',
               'היה', 'ממש', 'אנשים', 'הייתה', 'מדי', 'מצליחה', 'פעמים', 'אחרת', 'ירדתי', 'קורה', 'התחיל', 'בהתחלה',
               'מישהי', 'הבלוג', 'עולה', 'והכי', 'לכולם', 'חיי', 'האלו', 'לחדר', 'מתחיל', 'מכירה', 'קטנות', 'מוזר',
               'למשל', 'שבו', 'מודעת', 'היד', 'תחת', 'לחלק', 'במדרגות', 'מדהימים', 'צורה', 'ברמה', 'נראים', 'הבנות',
               'אליהן', 'שרירים', 'שינה', 'משלשלים', 'איתך', 'ומצד', 'המילה', 'מעכשיו', 'כלשהי', 'הארור', 'מאוהבת',
               'כולנו', 'חסה', 'לשקר', 'זוהי', 'עצמי', 'ביום', 'שהוא', 'חייבת', 'טובה', 'שנה', 'שבוע', 'העולם', 'פתאום',
               'בדרך', '10', 'מאמינה', 'יהיו', 'בטח', 'דרך', 'מתה', 'אליו', 'הזו', 'הצלחתי', 'הלב', 'נשמע', 'ויפה',
               'לבית', 'הצהריים', 'ברור', 'ועם', 'יוצאת', 'להסתיר', 'המיטה', 'שחור', 'ואמא', 'לנסוע', 'סובלת', 'נוספת',
               'לבן', 'שקט', 'מטורף', 'לעזאזל', 'אור', 'כולי', 'קילוגרמים', 'פשוטה', 'נפלתי', 'משותף', 'עצמכם', 'ראו',
               'בטוב', 'הו', 'לסיים', 'המקום', 'לירידה', 'שיניים', 'שיחה', 'בדבר', 'להשאיר', 'ההרזיה', 'המשחק', 'תשובה',
               'אלפי', 'היום', 'יום', 'אין', 'חושבת', 'החיים', 'לה', 'אל', 'קפה', 'מהר', 'הגעתי', 'שלהם', 'מכל',
               'אחרים', 'האנשים', 'מעל', 'להשמין', 'כואב', '25', 'וככה', 'אוכלים', 'שתי', 'בהמשך', 'נעים', 'כאלו',
               'מפסיקה', 'הסיפור', 'צעיר', 'שבאמת', 'גורמת', 'שלמות', 'ילד', 'שברגע', 'וכ', 'כח', 'עלייך', 'ובבוקר',
               'פחדתי', 'מוסיקה', 'עלינו', 'לידי', 'לפח', 'שלקחתי', 'שקוראים', 'הלך', 'תוצאות', 'במקומות', 'להוסיף',
               'הסתכל', 'שתצליחו', 'החולים', 'בואו', 'הנפילה', 'שעם', 'הארוחות', 'מה', 'יותר', 'לעצמי', 'פה', 'אתמול',
               'בי', 'אומרת', 'בת', 'זו', 'שני', 'שוקלת', 'בה', 'בשבילי', 'בריאה', 'ללא', 'בלוג', 'רגע', 'ליום',
               'ירקות', 'לכך', 'רזות', 'מעולם', 'מאחר', 'לגבי', 'שעד', 'התחילה', 'באוכל', 'מדובר', 'שרזיתי', 'להכניס',
               'אדמה', 'וכאלה', 'מחמאות', 'אופי', 'יורדים', 'אנרגיה', 'לבדוק', 'שמו', 'לציין', 'למידה', 'מסודר', 'ושום',
               'בעל', 'מכורה', 'חילוף', 'בייחוד', 'פרצוף', 'לעיתים', 'נולד', 'סופית', 'מוקדם', 'הפנים', 'עברה', 'הקטן',
               'יודעת', 'עדיין', 'בגלל', 'אפשר', 'שהיא', 'אותה', 'עלי', 'שהם', 'בזה', 'לפעמים', 'אמרתי', 'להמשיך',
               'האחרונה', 'להתחיל', 'שישי', 'להבין', 'שלוש', 'ראשון', 'ארוך', 'רוצים', 'חזרה', 'ביותר', 'חודשיים',
               'יצא', 'שאולי', 'מתחת', 'הכאב', 'לאוכל', 'הלכה', 'הלימודים', 'לראש', 'הרעב', 'שהכי', 'מידות', 'חלשה',
               'הטוב', 'ההתבגרות', 'והחלטתי', 'לשני', 'מלאת', 'החיוך', 'ושאני', 'אלף', 'ולעשות', 'זורם', 'בפייסבוק',
               'הרזיה', 'ולמרות', 'להיות', 'קצת', 'למה', 'דבר', 'לפני', 'לפחות', 'בכלל', 'ממני', 'בבוקר', 'כמובן',
               'ועוד', 'וכל', 'בערב', 'מעט', 'אמרו', 'רואה', 'שאכלתי', 'איתי', 'הבטן', 'שעה', 'בזמן', 'בן', 'חברות',
               'ואולי', 'ים', 'לשתות', 'קוראים', 'הרגליים', 'היכולת', 'ויותר', 'במהלך', 'כמוני', 'לאנורקסיה', 'גבוה',
               'מתכוונת', 'מאוחר', 'מהמשקל', 'טעים', 'אח', 'ותמיד', 'ואמר', 'עשרים', 'ממשיכה', 'לשלב', 'כשאתה', 'כוחות',
               'לראשון', 'בחנויות', 'שאומר', 'שיכולה', 'הרגשה', 'אבקת', 'התברר', 'שעלי', 'יש', 'איך', 'באמת', 'כן',
               'להרגיש', 'עליי', 'לבד', 'אצל', 'בעיה', 'האמת', 'לאמא', 'מאשר', 'כלל', 'תקופה', 'לפה', 'שכבר', 'להתמודד',
               'אמשיך', 'פאקינג', 'אמורה', 'כדאי', 'לבצע', 'הראשונה', 'קודם', 'רצון', 'והתחלתי', 'חדר', 'האהבה',
               'ואנחנו', 'וטוב', 'הראשונים', 'התעוררתי', 'כשהגעתי', 'לבריאות', 'עולם', 'וחברים', 'עוצר', 'לאדם',
               'מעורר', 'מעמד', 'ואני', 'פעם', 'לעשות', 'בכל', 'צריכה', 'למרות', 'רציתי', 'שלנו', 'ואת', 'לחשוב',
               'הדבר', 'כאלה', 'ואין', 'ואפילו', 'שיהיה', 'תוך', 'בחזרה', 'מושלם', 'לקנות', 'חדשה', 'לקום', 'כמות',
               'ככל', 'הסיבה', 'להשלים', 'שעכשיו', 'דומה', 'סיפור', 'המחשב', 'משמין', 'שקלו', 'ובדרך', 'מושלמים', 'צד',
               'שניתן', 'ובתמים', 'כולה', 'החומרים', 'מתמודדת', 'לעזוב', 'או', 'עכשיו', 'אחרי', 'משהו', 'יהיה', 'זאת',
               'במקום', 'חצי', 'מתחילה', 'בטוחה', 'לישון', 'ועכשיו', 'עליה', 'גדולה', 'וזהו', 'אלו', 'לעולם', '12',
               'עצוב', 'שהיו', 'שאוכל', 'ממנה', 'שלמה', 'לשמוע', 'בהמון', 'לרגע', 'בצד', 'עולים', 'הקטע', 'מובן',
               'ראשונה', 'ברחובות', 'ואוכלת', 'מגוחך', 'בולטות', 'שיטות', 'לפתוח', 'מעבירה', 'אגב', 'בשם', 'לבנה',
               'חיוורת', 'נחמדה', 'ולפני', 'ילך', 'השלישי', 'שליטה', 'בריאים', 'כי', 'כבר', 'גם', 'טוב', 'אחד', 'אולי',
               'דברים', 'אחר', 'כמעט', 'להגיע', 'להגיד', 'גדול', 'אדם', 'חוץ', 'הלכתי', 'ממנו', 'ואחרי', 'שכן', 'הבא',
               'נכנסתי', 'מעולה', 'קשר', 'מצב', 'אליהם', 'חבר', 'בנים', 'שפחות', 'עובדות', 'נקודה', 'ולאכול', 'הזדמנות',
               'שמנים', 'עצמית', 'סיפרה', 'בדיכאון', 'הלחץ', 'להוציא', 'סבלתי', '160', 'מכאן', 'המעבר', 'שלמרות',
               'באתי', 'פסיכולוגים', 'השנים', 'לקוחות', 'להעביר', 'ושל', 'כמו', 'הרבה', 'ככה', 'הכל', 'יכולה', 'תמיד',
               'לזה', 'האלה', 'הולכת', 'אותם', 'שהיה', 'התחלתי', 'מספיק', 'בשבוע', 'והיא', 'הראשון', 'השני', 'תמיכה',
               'למקום', 'נכנסת', 'לקרוא', 'הפסקתי', 'ירד', 'ולהיות', 'לוקחת', 'שקלתי', 'אישית', 'האדם', 'לשתף',
               'איבדתי', 'בעצמך', 'בוכה', 'ארזה', 'עזרה', 'שריר', 'ובכלל', 'השחרור', 'רגילים', 'תזונתיים', 'להתאים',
               'יוצאים', 'משום', 'הרופאים', 'לשלוח', 'סדר', 'היופי', 'קשורה', 'בסיס', 'כמה', 'הייתי', 'וזה', 'פשוט',
               'עד', 'קשה', 'אחת', 'פחות', 'איזה', 'בבית', 'לכל', 'לב', 'והוא', 'בעצם', 'מול', 'העובדה', 'אצלי', 'לתת',
               'בעיות', 'אמיתי', 'במה', 'חייב', 'לאורך', 'והיה', 'אתן', 'שמתי', 'ובאמת', 'להיראות', 'נהיה', 'בבלוג',
               'שלם', 'עדין', 'ישבתי', 'אחריי', 'חושב', 'הפסיק', 'מדברים', 'המשפט', 'יגיד', 'מתאימה', 'והייתה', 'להפך',
               'מהאנשים', 'בקטע', 'הצד', 'כרגיל', 'בושה', 'הסכמתי', 'החודש', 'מוות', 'הזה', 'שלא', 'שזה', 'בלי', 'כדי',
               'אותו', 'היו', 'לראות', 'בין', 'חודש', 'וכמה', 'שהייתי', 'לומר', 'חוזרת', 'האחרונות', 'בגיל', 'מותר',
               'שהגעתי', 'בדיקות', 'עצמם', 'אביב', 'לטוב', 'בעבר', 'נשברת', 'מילים', 'ארבע', 'עושות', 'ממשקל', 'הצליחו',
               'ממתקים', 'לדיכאונות', 'תורם', 'קראו', 'נמנעת', 'ענק', 'בני', 'מבחינתי']
